import type {
  AssessmentOption,
  AssessmentQuestion,
  MultiSelectQuestion,
  OrderingQuestion,
  SimletQuestion,
  SingleChoiceQuestion
} from "../assessmentTypes";

const option = (id: string, text: string, explanation: string): AssessmentOption => ({
  id,
  text,
  explanation
});

const four = (
  a: AssessmentOption,
  b: AssessmentOption,
  c: AssessmentOption,
  d: AssessmentOption
): [AssessmentOption, AssessmentOption, AssessmentOption, AssessmentOption] => [a, b, c, d];

const sequence = (a: string, b: string, c: string, d: string): [string, string, string, string] =>
  [a, b, c, d];

const single = (
  topicId: string,
  id: string,
  prompt: string,
  options: [AssessmentOption, AssessmentOption, AssessmentOption, AssessmentOption],
  answerId: string
): SingleChoiceQuestion => ({ id, topicId, prompt, type: "single", options, answerIds: [answerId] });

const multi = (
  topicId: string,
  id: string,
  prompt: string,
  options: [AssessmentOption, AssessmentOption, AssessmentOption, AssessmentOption],
  answerIds: [string, string]
): MultiSelectQuestion => ({ id, topicId, prompt, type: "multi-select", options, answerIds });

const ordering = (
  topicId: string,
  id: string,
  prompt: string,
  items: [AssessmentOption, AssessmentOption, AssessmentOption, AssessmentOption],
  correctOrder: [string, string, string, string]
): OrderingQuestion => ({ id, topicId, prompt, type: "ordering", items, correctOrder });

const simlet = (
  topicId: string,
  id: string,
  prompt: string,
  output: string,
  options: [AssessmentOption, AssessmentOption, AssessmentOption, AssessmentOption],
  answerIds: [string, string]
): SimletQuestion => ({ id, topicId, prompt, type: "simlet", output, options, answerIds });

const questions: AssessmentQuestion[] = [
  // Security fundamentals
  single("threats", "threats-01", "A public-facing router has an unused web-management service enabled. Which action most directly reduces its exposure?",
    four(option("threats-01-a", "Disable the unused service", "Correct: removing an unnecessary listening service reduces the attack surface."),
      option("threats-01-b", "Increase the interface MTU", "MTU changes packet sizing and do not disable the exposed management service."),
      option("threats-01-c", "Add a second default route", "A backup route improves path availability but leaves the vulnerable service reachable."),
      option("threats-01-d", "Rename the router", "A hostname change does not restrict access to a listening service.")), "threats-01-a"),
  single("threats", "threats-02", "Which statement best distinguishes a vulnerability from a threat?",
    four(option("threats-02-a", "A vulnerability is a weakness; a threat is a potential source of harm", "Correct: a weakness may be exploited by a threat actor or event."),
      option("threats-02-b", "A vulnerability is an attack; a threat is a patch", "An attack may exploit a vulnerability; a patch can mitigate one."),
      option("threats-02-c", "A threat is always a device failure", "Threats include malicious actors, mistakes, and environmental events."),
      option("threats-02-d", "The terms mean the same thing", "They are related but describe different parts of risk.")), "threats-02-a"),
  single("threats", "threats-03", "A switch's management interface is reachable from every user VLAN. What is the most appropriate first mitigation?",
    four(option("threats-03-a", "Restrict management access to a trusted management network", "Correct: limiting reachable sources reduces exposure while preserving administration."),
      option("threats-03-b", "Enable dynamic routing on every VLAN", "Routing protocol changes do not limit management-plane access."),
      option("threats-03-c", "Increase the MAC address aging timer", "MAC aging affects forwarding-table behavior, not management reachability."),
      option("threats-03-d", "Disable logging", "Removing logs reduces visibility and does not block unauthorized access.")), "threats-03-a"),
  single("threats", "threats-04", "Which control is most useful for detecting repeated failed logins against network devices?",
    four(option("threats-04-a", "Centralized authentication and log monitoring", "Correct: centralized records make repeated failures easier to correlate and alert on."),
      option("threats-04-b", "A larger routing table", "Route capacity does not provide login-event visibility."),
      option("threats-04-c", "An unused VLAN", "An unused VLAN has no direct effect on authentication monitoring."),
      option("threats-04-d", "A longer console cable", "Physical cable length does not detect authentication attempts.")), "threats-04-a"),
  multi("threats", "threats-05", "Which TWO actions reduce the likelihood or impact of unauthorized device access?",
    four(option("threats-05-a", "Use unique, strong administrative credentials", "Correct: unique credentials limit guessing and reduce reuse-related compromise."),
      option("threats-05-b", "Permit remote management from any source", "Broad reachability increases exposure rather than reducing it."),
      option("threats-05-c", "Apply security updates after testing", "Correct: tested updates address known weaknesses while managing change risk."),
      option("threats-05-d", "Share one administrator account among all staff", "Shared accounts undermine accountability and encourage credential reuse.")), ["threats-05-a", "threats-05-c"]),
  multi("threats", "threats-06", "Which TWO observations are indicators worth investigating as possible security incidents?",
    four(option("threats-06-a", "A management login succeeds from an unapproved subnet", "Correct: an unexpected source may indicate compromised credentials or policy failure."),
      option("threats-06-b", "A configured interface reports its expected line protocol", "Expected interface state alone is not evidence of an incident."),
      option("threats-06-c", "A configuration changes outside the approved window", "Correct: unexplained changes may signal misuse or an uncontrolled process."),
      option("threats-06-d", "A documented backup completes on schedule", "A normal scheduled backup is not by itself suspicious.")), ["threats-06-a", "threats-06-c"]),
  ordering("threats", "threats-07", "Order a basic response to a confirmed, unauthorized management session, prioritizing containment and evidence.",
    four(option("threats-07-a", "Preserve relevant logs and record the event", "Evidence should be retained so the incident can be investigated."),
      option("threats-07-b", "Confirm and scope the unexpected session", "Validation identifies affected devices and access before response."),
      option("threats-07-c", "Contain access using the incident procedure", "After scoping, block or isolate the unauthorized path."),
      option("threats-07-d", "Review cause and restore approved access securely", "Follow-up remediation prevents recurrence and restores intended service.")),
    sequence("threats-07-b", "threats-07-a", "threats-07-c", "threats-07-d")),
  simlet("threats", "threats-08", "Use the illustrative event excerpt to identify TWO security concerns requiring follow-up.",
    "Illustrative event excerpt (not device output):\n18:42:11 login success user=netadmin source=198.51.100.77\n18:43:02 config saved by user=netadmin\nExpected management subnet: 10.20.0.0/24",
    four(option("threats-08-a", "The successful login came from outside the expected management subnet", "Correct: the source address is outside 10.20.0.0/24 and requires validation."),
      option("threats-08-b", "A configuration was saved after login", "Correct: a change immediately after unexpected access should be reviewed and attributed."),
      option("threats-08-c", "The excerpt proves that the password was weak", "The log provides no password-strength evidence."),
      option("threats-08-d", "The address is a private RFC 1918 address", "198.51.100.77 is a documentation address, not a private RFC 1918 address.")), ["threats-08-a", "threats-08-b"]),

  single("security-programs", "security-programs-01", "What is the primary purpose of an acceptable-use policy?",
    four(option("security-programs-01-a", "Define permitted and prohibited use of organizational resources", "Correct: the policy sets user expectations for appropriate resource use."),
      option("security-programs-01-b", "Choose the shortest path through an OSPF area", "Route calculation is unrelated to acceptable-use guidance."),
      option("security-programs-01-c", "Automatically encrypt every network packet", "A written policy does not itself implement packet encryption."),
      option("security-programs-01-d", "Replace all incident-response procedures", "Acceptable-use rules complement, rather than replace, incident handling.")), "security-programs-01-a"),
  single("security-programs", "security-programs-02", "A least-privilege policy should grant an operator which access?",
    four(option("security-programs-02-a", "Only the access needed for assigned duties", "Correct: least privilege limits unnecessary permissions and potential impact."),
      option("security-programs-02-b", "Full administrator rights by default", "Defaulting to broad access contradicts least privilege."),
      option("security-programs-02-c", "No access to any operational system", "A blanket denial prevents legitimate assigned work."),
      option("security-programs-02-d", "The same rights as every other employee", "Roles and duties differ, so uniform access is not least privilege.")), "security-programs-02-a"),
  single("security-programs", "security-programs-03", "Why should an organization maintain a documented change-management process?",
    four(option("security-programs-03-a", "To assess, approve, schedule, and review changes consistently", "Correct: a defined process controls risk and improves traceability."),
      option("security-programs-03-b", "To guarantee that every change has no outage", "Review reduces risk but cannot guarantee zero impact."),
      option("security-programs-03-c", "To eliminate the need for configuration backups", "Backups remain useful for recovery and rollback."),
      option("security-programs-03-d", "To authorize undocumented emergency changes permanently", "Emergency paths should still be documented and reviewed afterward.")), "security-programs-03-a"),
  single("security-programs", "security-programs-04", "Which policy element most directly establishes how quickly a suspected security event must be reported?",
    four(option("security-programs-04-a", "Incident reporting requirements", "Correct: reporting timelines and channels define escalation expectations."),
      option("security-programs-04-b", "Address allocation plan", "Addressing documents do not define security incident escalation."),
      option("security-programs-04-c", "Wireless channel plan", "Radio channel selection is unrelated to reporting obligations."),
      option("security-programs-04-d", "Hardware inventory format", "Inventory structure does not set event-reporting deadlines.")), "security-programs-04-a"),
  multi("security-programs", "security-programs-05", "Which TWO practices help make a security policy effective over time?",
    four(option("security-programs-05-a", "Assign an owner and review it periodically", "Correct: ownership and scheduled review keep policy current and maintained."),
      option("security-programs-05-b", "Keep the policy inaccessible to staff", "Staff cannot follow requirements they cannot discover."),
      option("security-programs-05-c", "Communicate requirements and provide relevant training", "Correct: users need to understand applicable expectations and procedures."),
      option("security-programs-05-d", "Allow each team to silently override it", "Uncontrolled exceptions erode consistent policy enforcement.")), ["security-programs-05-a", "security-programs-05-c"]),
  multi("security-programs", "security-programs-06", "Which TWO items belong in a practical device-hardening standard?",
    four(option("security-programs-06-a", "Disable services that are not required", "Correct: reducing unused services reduces attack surface."),
      option("security-programs-06-b", "Use identical shared passwords on all devices", "Shared passwords weaken accountability and amplify credential compromise."),
      option("security-programs-06-c", "Specify secure management protocols and approved sources", "Correct: the standard can define encrypted protocols and management restrictions."),
      option("security-programs-06-d", "Leave default accounts undocumented", "Default accounts must be assessed and secured, not ignored.")), ["security-programs-06-a", "security-programs-06-c"]),
  ordering("security-programs", "security-programs-07", "Order a controlled routine network change from proposal through closeout.",
    four(option("security-programs-07-a", "Implement during the approved window", "Execution follows authorization and scheduling."),
      option("security-programs-07-b", "Document the request, scope, and risk", "A complete request gives reviewers the facts needed to evaluate it."),
      option("security-programs-07-c", "Validate service and record the outcome", "Post-change checks determine whether objectives were met."),
      option("security-programs-07-d", "Obtain required approval and schedule the window", "Approval and scheduling precede implementation.")),
    sequence("security-programs-07-b", "security-programs-07-d", "security-programs-07-a", "security-programs-07-c")),
  simlet("security-programs", "security-programs-08", "Read the illustrative policy excerpt. Which TWO conclusions follow directly?",
    "Illustrative policy excerpt (not device output):\nPrivileged access: named accounts only.\nEmergency changes: notify the change owner within one business day.\nExceptions: require documented owner approval.",
    four(option("security-programs-08-a", "A shared named-admin login conflicts with the stated access rule", "Correct: privileged access is explicitly limited to named accounts."),
      option("security-programs-08-b", "An emergency change must be reported to its owner within the stated period", "Correct: the excerpt specifies notification within one business day."),
      option("security-programs-08-c", "No approval is needed for an exception", "The excerpt requires documented owner approval for exceptions."),
      option("security-programs-08-d", "The policy mandates changing passwords every 30 days", "No password rotation interval appears in the excerpt.")), ["security-programs-08-a", "security-programs-08-b"]),

  single("device-access", "device-access-01", "Which protocol should an administrator use for encrypted command-line management of a router?",
    four(option("device-access-01-a", "SSH", "Correct: SSH encrypts remote command-line sessions."),
      option("device-access-01-b", "Telnet", "Telnet sends session data, including credentials, without SSH-style encryption."),
      option("device-access-01-c", "TFTP", "TFTP transfers files and does not provide an encrypted CLI session."),
      option("device-access-01-d", "SNMPv1", "SNMPv1 is a management protocol, not an encrypted interactive CLI.")), "device-access-01-a"),
  single("device-access", "device-access-02", "How should a device's privileged secret be handled in a secure configuration?",
    four(option("device-access-02-a", "Store it using a supported protected secret mechanism", "Correct: protected storage avoids exposing a clear-text privileged credential."),
      option("device-access-02-b", "Place the clear-text password in a public banner", "A banner is visible to users and must not contain credentials."),
      option("device-access-02-c", "Reuse a user's personal password", "Personal-password reuse increases impact and reduces accountability."),
      option("device-access-02-d", "Disable all authentication", "Removing authentication makes privileged access uncontrolled.")), "device-access-02-a"),
  single("device-access", "device-access-03", "Which control most directly limits which hosts can initiate device management sessions?",
    four(option("device-access-03-a", "A management-plane access list", "Correct: a management ACL can restrict session sources to approved addresses."),
      option("device-access-03-b", "A larger console history buffer", "History retention does not control who can connect."),
      option("device-access-03-c", "A trunk allowed-VLAN list on an unrelated port", "An unrelated trunk restriction does not limit management-plane sources."),
      option("device-access-03-d", "A spanning-tree root priority change", "Spanning-tree election does not control remote management access.")), "device-access-03-a"),
  single("device-access", "device-access-04", "Why configure an explicit login authentication method on remote lines?",
    four(option("device-access-04-a", "To require the intended credential source when sessions begin", "Correct: explicit authentication prevents unintended unauthenticated or local-only behavior."),
      option("device-access-04-b", "To enable IPv6 forwarding", "Line authentication has no role in forwarding IPv6 packets."),
      option("device-access-04-c", "To encrypt all transit traffic", "Login authentication does not encrypt data traffic traversing the device."),
      option("device-access-04-d", "To make a console cable unnecessary", "Remote line authentication does not replace physical console access.")), "device-access-04-a"),
  multi("device-access", "device-access-05", "Which TWO measures strengthen remote device administration?",
    four(option("device-access-05-a", "Use SSH and disable unused insecure remote services", "Correct: SSH protects the session and disabling unused services reduces exposure."),
      option("device-access-05-b", "Permit management from every routed interface", "Unrestricted reachability expands the attack surface."),
      option("device-access-05-c", "Restrict management sources to approved hosts or subnets", "Correct: source restrictions reduce who can attempt access."),
      option("device-access-05-d", "Put shared credentials in an unencrypted script", "That exposes credentials and prevents individual accountability.")), ["device-access-05-a", "device-access-05-c"]),
  multi("device-access", "device-access-06", "Which TWO practices help protect administrative credentials?",
    four(option("device-access-06-a", "Use unique accounts for administrators", "Correct: named identities improve accountability and support individual access control."),
      option("device-access-06-b", "Store secrets in an approved protected credential store", "Correct: protected storage avoids casual exposure in files or notes."),
      option("device-access-06-c", "Send passwords in clear text through chat", "Clear-text transmission can expose credentials to unintended recipients."),
      option("device-access-06-d", "Use the vendor default password indefinitely", "Default credentials are widely known and should be changed.")), ["device-access-06-a", "device-access-06-b"]),
  ordering("device-access", "device-access-07", "Order the safe preparation of SSH access on a newly hardened device.",
    four(option("device-access-07-a", "Enable SSH on the intended remote-access lines", "SSH is enabled on the selected management lines after prerequisites."),
      option("device-access-07-b", "Set a hostname and domain identity required for key generation", "Device identity settings are prerequisites for generating a key pair on many platforms."),
      option("device-access-07-c", "Generate the device's SSH key pair", "The key pair provides the cryptographic identity needed by SSH."),
      option("device-access-07-d", "Configure authenticated users and restrict allowed sources", "Accounts and source restrictions define who may use the service.")),
    sequence("device-access-07-b", "device-access-07-d", "device-access-07-c", "device-access-07-a")),
  simlet("device-access", "device-access-08", "From the illustrative management summary, select TWO supported findings.",
    "Illustrative status summary (not device output):\nRemote CLI: SSH enabled\nRemote CLI: Telnet enabled\nAllowed source range: 0.0.0.0/0\nLocal admin account: enabled",
    four(option("device-access-08-a", "Telnet remains an insecure remote service that should be removed if unnecessary", "Correct: Telnet does not protect the management session like SSH."),
      option("device-access-08-b", "The source range permits connections from any IPv4 source", "Correct: 0.0.0.0/0 covers all IPv4 addresses."),
      option("device-access-08-c", "SSH is disabled", "The summary explicitly states that SSH is enabled."),
      option("device-access-08-d", "There is no local administrator account", "The summary explicitly reports an enabled local admin account.")), ["device-access-08-a", "device-access-08-b"]),

  single("acls", "acls-01", "An IPv4 ACL has `deny ip any any` before a later permit. What happens to packets matching the later permit?",
    four(option("acls-01-a", "They are denied by the earlier matching ACE", "Correct: ACL entries are evaluated in order and processing stops at the first match."),
      option("acls-01-b", "They are permitted because permit always overrides deny", "ACLs do not use a global permit-overrides-deny rule."),
      option("acls-01-c", "They are forwarded until the next router", "The matching deny discards the packet at this ACL."),
      option("acls-01-d", "The router randomly selects an entry", "ACL evaluation is deterministic and ordered.")), "acls-01-a"),
  single("acls", "acls-02", "What is the effect of the implicit final rule in a typical ACL?",
    four(option("acls-02-a", "Traffic not matched by an explicit permit is denied", "Correct: the implicit deny blocks unmatched traffic."),
      option("acls-02-b", "All unmatched traffic is permitted", "Unmatched traffic is denied, not permitted."),
      option("acls-02-c", "The ACL is ignored unless it contains logging", "Logging is not required for ACL enforcement."),
      option("acls-02-d", "Only broadcast packets are denied", "The implicit deny applies to any packet not explicitly permitted.")), "acls-02-a"),
  single("acls", "acls-03", "A standard IPv4 ACL is intended to permit a source subnet. Which field does it primarily match?",
    four(option("acls-03-a", "The packet's source IPv4 address", "Correct: a standard ACL primarily filters on source address."),
      option("acls-03-b", "The destination TCP port", "Destination ports are available to extended ACL matching, not standard ACL source-only matching."),
      option("acls-03-c", "The Ethernet frame's destination MAC only", "An IP ACL matches Layer 3 packet fields, not only the Ethernet destination MAC."),
      option("acls-03-d", "The OSPF cost", "OSPF route metric is unrelated to ACL packet matching.")), "acls-03-a"),
  single("acls", "acls-04", "Where is an extended ACL commonly placed to block unwanted traffic close to its source?",
    four(option("acls-04-a", "Near the traffic source", "Correct: early filtering prevents unwanted traffic from crossing the rest of the network."),
      option("acls-04-b", "Only on the destination host's console port", "A console port is not an IP packet-filtering interface."),
      option("acls-04-c", "At the farthest possible point from source", "That allows denied traffic to consume network resources before filtering."),
      option("acls-04-d", "On a switch's unused VLAN", "An unrelated unused VLAN will not filter the source traffic.")), "acls-04-a"),
  multi("acls", "acls-05", "An ACL must allow HTTPS from 192.0.2.0/24 to server 203.0.113.20 and block other sources from that server. Which TWO rule properties are required?",
    four(option("acls-05-a", "Permit the source subnet to destination host TCP port 443", "Correct: this matches the intended sources, server, protocol, and service."),
      option("acls-05-b", "Permit all IP traffic before the specific rule", "A broad earlier permit would bypass the intended restriction."),
      option("acls-05-c", "Place a deny for remaining traffic to the server after the permit", "Correct: the later deny blocks other matching sources while preserving the exception."),
      option("acls-05-d", "Match UDP port 443 only", "HTTPS ordinarily uses TCP; UDP-only matching misses the stated service.")), ["acls-05-a", "acls-05-c"]),
  multi("acls", "acls-06", "Which TWO checks are useful when an intended ACL policy does not work?",
    four(option("acls-06-a", "Check ACE order and the implicit deny", "Correct: an earlier match or unmatched traffic may be causing a drop."),
      option("acls-06-b", "Assume a permit later in the list overrides every deny", "First-match order means a later permit cannot override an earlier match."),
      option("acls-06-c", "Verify the ACL is applied in the correct direction and interface", "Correct: a correct list attached at the wrong point or direction may not govern the traffic."),
      option("acls-06-d", "Change the router hostname", "Hostname changes do not correct packet-filter behavior.")), ["acls-06-a", "acls-06-c"]),
  ordering("acls", "acls-07", "Order these conceptual steps to build and verify a narrowly scoped ACL policy.",
    four(option("acls-07-a", "Apply the ACL at the intended interface and direction", "Correct placement makes the rules govern the intended traffic path."),
      option("acls-07-b", "Identify source, destination, protocol, and required service", "The traffic requirement must be clear before writing rules."),
      option("acls-07-c", "Test both permitted and denied traffic and inspect counters", "Validation checks policy behavior and helps detect unintended matches."),
      option("acls-07-d", "Write specific permit and deny entries in deliberate order", "Rule ordering implements the identified policy before application.")),
    sequence("acls-07-b", "acls-07-d", "acls-07-a", "acls-07-c")),
  simlet("acls", "acls-08", "Read this illustrative ACL counter excerpt. Which TWO conclusions are supported?",
    "Illustrative ACL excerpt (not device output):\n10 permit tcp 192.0.2.0/24 host 203.0.113.20 eq 443 (hits 8)\n20 deny ip any host 203.0.113.20 (hits 3)\n30 permit ip any any (hits 41)",
    four(option("acls-08-a", "At least eight packets matched the HTTPS permit entry", "Correct: the displayed counter for ACE 10 is eight hits."),
      option("acls-08-b", "At least three packets matched the deny entry for the server", "Correct: ACE 20 shows three hits."),
      option("acls-08-c", "The deny entry is unreachable because all traffic is permitted first", "ACE 10 is narrow; other traffic can reach the subsequent deny."),
      option("acls-08-d", "No other traffic is allowed by this ACL", "ACE 30 explicitly permits other IP traffic and has hits.")), ["acls-08-a", "acls-08-b"]),

  single("layer2-security", "layer2-security-01", "What does switch port security primarily control on an access port?",
    four(option("layer2-security-01-a", "Which and how many source MAC addresses may use the port", "Correct: port security can constrain learned or configured MAC addresses."),
      option("layer2-security-01-b", "Which OSPF area the switch joins", "Port security does not configure Layer 3 routing areas."),
      option("layer2-security-01-c", "The encryption algorithm used by SSH", "SSH encryption is unrelated to Layer 2 port security."),
      option("layer2-security-01-d", "The subnet mask assigned by DHCP", "Port security does not assign client IP parameters.")), "layer2-security-01-a"),
  single("layer2-security", "layer2-security-02", "What is a typical purpose of DHCP snooping on a Layer 2 switch?",
    four(option("layer2-security-02-a", "Distinguish trusted DHCP-server-facing ports from untrusted ports", "Correct: snooping can prevent unauthorized DHCP server replies arriving on untrusted ports."),
      option("layer2-security-02-b", "Encrypt all DHCP messages end to end", "DHCP snooping does not provide general DHCP message encryption."),
      option("layer2-security-02-c", "Elect the spanning-tree root bridge", "Root election is a spanning-tree function, not DHCP snooping."),
      option("layer2-security-02-d", "Translate private addresses to public addresses", "Address translation is a router function, not DHCP snooping.")), "layer2-security-02-a"),
  single("layer2-security", "layer2-security-03", "What is the main security benefit of Dynamic ARP Inspection when correctly configured with a DHCP snooping binding table?",
    four(option("layer2-security-03-a", "It validates ARP information against trusted bindings", "Correct: DAI can reject inconsistent ARP messages that could support spoofing."),
      option("layer2-security-03-b", "It encrypts ARP frames", "DAI validates ARP; it does not encrypt Ethernet frames."),
      option("layer2-security-03-c", "It prevents every Layer 2 loop", "Spanning Tree, not DAI, prevents Layer 2 forwarding loops."),
      option("layer2-security-03-d", "It assigns static routes to clients", "DAI does not provide routing or client route assignment.")), "layer2-security-03-a"),
  single("layer2-security", "layer2-security-04", "A user-facing switch port should transition quickly to forwarding but shut down if it receives a BPDU. Which feature combination fits?",
    four(option("layer2-security-04-a", "PortFast with BPDU Guard", "Correct: PortFast speeds edge forwarding, while BPDU Guard protects against unexpected bridge BPDUs."),
      option("layer2-security-04-b", "Root Guard with trunk negotiation", "Root Guard protects root placement; trunk negotiation does not provide edge fast start."),
      option("layer2-security-04-c", "DHCP snooping with NTP", "These features do not provide the requested spanning-tree edge behavior."),
      option("layer2-security-04-d", "Port security with an EtherChannel", "Those features do not replace PortFast and BPDU Guard.")), "layer2-security-04-a"),
  multi("layer2-security", "layer2-security-05", "Which TWO protections help mitigate common rogue-server or address-spoofing attacks on access VLANs?",
    four(option("layer2-security-05-a", "DHCP snooping with only legitimate server-facing ports trusted", "Correct: untrusted ports cannot freely inject server replies."),
      option("layer2-security-05-b", "Trust every user-facing DHCP-snooping port", "Trusting all edge ports defeats the intended rogue-server protection."),
      option("layer2-security-05-c", "Dynamic ARP Inspection using appropriate trusted bindings", "Correct: validation can reject forged ARP claims inconsistent with trusted bindings."),
      option("layer2-security-05-d", "Disable all switch port counters", "Counters are observational and disabling them does not stop spoofing.")), ["layer2-security-05-a", "layer2-security-05-c"]),
  multi("layer2-security", "layer2-security-06", "Which TWO statements about port-security violation actions are accurate?",
    four(option("layer2-security-06-a", "A violation can occur when an unauthorized source MAC appears", "Correct: a source outside configured secure-MAC limits can trigger a violation."),
      option("layer2-security-06-b", "A violation always changes the VLAN's gateway address", "Port security does not alter the VLAN gateway."),
      option("layer2-security-06-c", "Violation modes differ in whether traffic is dropped, logged, or the port is shut down", "Correct: actions vary by configured mode, such as protect, restrict, or shutdown."),
      option("layer2-security-06-d", "Port security encrypts the endpoint's Ethernet frames", "MAC limiting does not encrypt Layer 2 payloads.")), ["layer2-security-06-a", "layer2-security-06-c"]),
  ordering("layer2-security", "layer2-security-07", "Order a basic DHCP-snooping deployment on an access switch.",
    four(option("layer2-security-07-a", "Enable DHCP snooping for the required VLANs", "Snooping must be activated for the VLANs being protected."),
      option("layer2-security-07-b", "Identify the legitimate DHCP-server path", "The legitimate server-facing path must be known before deciding what to trust."),
      option("layer2-security-07-c", "Trust only the appropriate server-facing interface", "Trusted status belongs on the port where legitimate server replies arrive."),
      option("layer2-security-07-d", "Validate client leases and test a rogue reply path", "Testing checks legitimate operation and whether untrusted replies are blocked.")),
    sequence("layer2-security-07-b", "layer2-security-07-a", "layer2-security-07-c", "layer2-security-07-d")),
  simlet("layer2-security", "layer2-security-08", "Use the illustrative switch summary to identify TWO security-relevant facts.",
    "Illustrative port summary (not device output):\nGi1/0/8 mode=access vlan=30 port-security=enabled max=1 learned=1\nGi1/0/8 violation=restrict\nGi1/0/24 dhcp-snooping-trust=yes role=access-user",
    four(option("layer2-security-08-a", "Gi1/0/8 is limited to one secure source MAC", "Correct: its configured maximum is one and one is learned."),
      option("layer2-security-08-b", "The user-facing Gi1/0/24 is trusted for DHCP snooping", "Correct: the summary explicitly marks the user-role port trusted, which warrants checking."),
      option("layer2-security-08-c", "Gi1/0/8 is configured to shut down on violation", "The displayed violation action is restrict, not shutdown."),
      option("layer2-security-08-d", "Gi1/0/8 is a routed Layer 3 port", "The summary identifies it as an access port in VLAN 30.")), ["layer2-security-08-a", "layer2-security-08-b"]),

  single("aaa", "aaa-01", "In AAA, which function verifies a user's claimed identity?",
    four(option("aaa-01-a", "Authentication", "Correct: authentication establishes identity from credentials or another factor."),
      option("aaa-01-b", "Authorization", "Authorization determines what an authenticated identity may do."),
      option("aaa-01-c", "Accounting", "Accounting records activity such as sessions or commands."),
      option("aaa-01-d", "Address translation", "NAT translates addresses and is not an AAA function.")), "aaa-01-a"),
  single("aaa", "aaa-02", "After a network operator logs in successfully, which AAA function determines whether the operator may run a configuration command?",
    four(option("aaa-02-a", "Authorization", "Correct: authorization evaluates permissions for requested resources or commands."),
      option("aaa-02-b", "Authentication", "Authentication has already verified identity; it does not by itself grant command rights."),
      option("aaa-02-c", "Accounting", "Accounting records activity rather than granting command permission."),
      option("aaa-02-d", "Encryption", "Encryption protects confidentiality but does not assign command privileges.")), "aaa-02-a"),
  single("aaa", "aaa-03", "Which AAA function records when an administrator logged in and which commands were used?",
    four(option("aaa-03-a", "Accounting", "Correct: accounting captures session and activity records for review."),
      option("aaa-03-b", "Authentication", "Authentication verifies identity rather than keeping the activity record."),
      option("aaa-03-c", "Authorization", "Authorization grants or denies permitted actions rather than recording them."),
      option("aaa-03-d", "Route redistribution", "Route redistribution is unrelated to AAA records.")), "aaa-03-a"),
  single("aaa", "aaa-04", "Why configure a local authentication fallback when remote AAA servers are used?",
    four(option("aaa-04-a", "To preserve a controlled access path if the remote service is unavailable", "Correct: an explicitly configured fallback can support administration during an AAA outage."),
      option("aaa-04-b", "To make every remote login bypass authentication", "A fallback should remain authenticated and controlled."),
      option("aaa-04-c", "To duplicate all remote accounting records automatically", "Local fallback does not inherently replicate remote accounting records."),
      option("aaa-04-d", "To force user traffic through the AAA server", "AAA authenticates access; it is not a data-plane traffic path.")), "aaa-04-a"),
  multi("aaa", "aaa-05", "Which TWO statements correctly describe AAA roles?",
    four(option("aaa-05-a", "Authentication confirms the identity associated with presented credentials", "Correct: it checks who the user is."),
      option("aaa-05-b", "Authorization records each command for an audit", "Command recording is an accounting role; authorization decides access."),
      option("aaa-05-c", "Authorization controls what an authenticated user may access", "Correct: authorization applies permissions after identity is established."),
      option("aaa-05-d", "Accounting chooses the user's password", "Password verification belongs to authentication, not accounting.")), ["aaa-05-a", "aaa-05-c"]),
  multi("aaa", "aaa-06", "Which TWO benefits can centralized AAA provide for network-device administration?",
    four(option("aaa-06-a", "Consistent identity policy across multiple devices", "Correct: central policy avoids maintaining unrelated local identity sets on every device."),
      option("aaa-06-b", "A record of access and requested actions", "Correct: accounting can provide centralized audit information."),
      option("aaa-06-c", "Guaranteed availability even if all AAA servers fail", "Centralization does not guarantee service during a complete outage; fallback planning is needed."),
      option("aaa-06-d", "Automatic encryption of every user data flow", "AAA does not encrypt all forwarded traffic.")), ["aaa-06-a", "aaa-06-b"]),
  ordering("aaa", "aaa-07", "Order the AAA stages for a user who logs in and then requests a privileged command.",
    four(option("aaa-07-a", "Record the session or command activity", "Accounting stores the relevant activity record."),
      option("aaa-07-b", "Verify the user's identity", "Authentication establishes who is requesting access."),
      option("aaa-07-c", "Evaluate permission for the requested command", "Authorization determines whether the authenticated user may perform it."),
      option("aaa-07-d", "Allow or deny the requested command based on the decision", "The device enforces the authorization result.")),
    sequence("aaa-07-b", "aaa-07-c", "aaa-07-d", "aaa-07-a")),
  simlet("aaa", "aaa-08", "Read the illustrative AAA event trace. Which TWO interpretations are correct?",
    "Illustrative AAA trace (not device output):\n18:01 AUTH user=lee result=success\n18:02 AUTHOR user=lee command=show ip route result=permit\n18:04 ACCOUNT user=lee command=configure terminal",
    four(option("aaa-08-a", "The identity check for lee succeeded", "Correct: the authentication event reports success."),
      option("aaa-08-b", "The trace explicitly shows authorization denied the show command", "It reports permit, not deny."),
      option("aaa-08-c", "An accounting record was generated for a configuration command", "Correct: the final line is an accounting event for configure terminal."),
      option("aaa-08-d", "The trace proves the configuration command completed successfully", "An accounting event alone does not state the command's completion result.")), ["aaa-08-a", "aaa-08-c"]),

  single("vpn", "vpn-01", "What is the primary security purpose of a VPN tunnel across an untrusted network?",
    four(option("vpn-01-a", "Protect traffic between tunnel endpoints using security services such as encryption", "Correct: a VPN tunnel can protect data in transit across an untrusted path."),
      option("vpn-01-b", "Guarantee that every endpoint is free of malware", "A VPN does not inspect or guarantee the health of every endpoint."),
      option("vpn-01-c", "Replace all routing decisions on the public internet", "Tunneling does not replace the underlying network's routing."),
      option("vpn-01-d", "Make an internal resource publicly accessible without controls", "A VPN can limit access, but does not make resources public by itself.")), "vpn-01-a"),
  single("vpn", "vpn-02", "Which design most closely describes a site-to-site VPN?",
    four(option("vpn-02-a", "Security gateways connect the networks of two locations", "Correct: site-to-site VPNs commonly establish protected connectivity between gateways."),
      option("vpn-02-b", "A single user encrypts a file on a laptop", "File encryption is not a network tunnel between sites."),
      option("vpn-02-c", "A switch tags Ethernet frames for a VLAN", "VLAN tagging is Layer 2 segmentation, not a VPN."),
      option("vpn-02-d", "A DNS resolver translates a hostname", "DNS resolution does not establish a protected site tunnel.")), "vpn-02-a"),
  single("vpn", "vpn-03", "Which VPN type is commonly used by an individual off-site employee to reach internal services?",
    four(option("vpn-03-a", "Remote-access VPN", "Correct: remote-access VPNs connect an individual endpoint to organizational resources."),
      option("vpn-03-b", "Site-to-site VPN only", "Site-to-site VPNs connect network locations rather than an individual client session."),
      option("vpn-03-c", "A native VLAN", "A native VLAN is a trunking concept, not a remote-access tunnel."),
      option("vpn-03-d", "A loopback interface", "A loopback is a logical interface and provides no VPN connection.")), "vpn-03-a"),
  single("vpn", "vpn-04", "What does tunnel encryption provide for VPN traffic while it crosses an untrusted path?",
    four(option("vpn-04-a", "Confidentiality against passive observation of the protected payload", "Correct: encryption makes the protected contents unreadable to observers without keys."),
      option("vpn-04-b", "Proof that the remote endpoint has no vulnerabilities", "Encryption does not perform an endpoint security assessment."),
      option("vpn-04-c", "A guarantee that packets cannot be dropped", "Encryption does not ensure availability or delivery."),
      option("vpn-04-d", "Automatic authorization for every internal service", "VPN establishment and resource authorization are separate access-control decisions.")), "vpn-04-a"),
  multi("vpn", "vpn-05", "Which TWO elements are commonly important to establishing a secure VPN peer relationship?",
    four(option("vpn-05-a", "Compatible security parameters at both tunnel endpoints", "Correct: peers need compatible protocols, algorithms, and negotiation settings."),
      option("vpn-05-b", "Identical inside host addresses at both sites", "Overlapping address plans can complicate routing and are not a required security parameter."),
      option("vpn-05-c", "A mutually accepted authentication method or credential", "Correct: peers need a way to authenticate one another."),
      option("vpn-05-d", "A shared unencrypted password embedded in user traffic", "This is unsafe and is not a valid secure peer-authentication design.")), ["vpn-05-a", "vpn-05-c"]),
  multi("vpn", "vpn-06", "Which TWO statements are sound VPN security practices?",
    four(option("vpn-06-a", "Use strong peer authentication and protect credentials or keys", "Correct: secure key handling and authentication reduce impersonation risk."),
      option("vpn-06-b", "Allow every authenticated remote user unrestricted internal access", "Authentication alone should not replace least-privilege authorization."),
      option("vpn-06-c", "Limit tunneled access to the resources required by the user or site", "Correct: least-privilege access limits impact if an account or endpoint is compromised."),
      option("vpn-06-d", "Assume a tunnel removes the need for endpoint security", "A VPN does not protect internal systems from a compromised client.")), ["vpn-06-a", "vpn-06-c"]),
  ordering("vpn", "vpn-07", "Order high-level steps for bringing up a planned site-to-site VPN.",
    four(option("vpn-07-a", "Verify protected reachability and monitor the tunnel", "Testing confirms the tunnel and allowed traffic work as intended."),
      option("vpn-07-b", "Agree on peer identities, protected networks, and security parameters", "Both ends need an aligned design and policy before configuration."),
      option("vpn-07-c", "Configure compatible settings and credentials at both peers", "The peers must be configured to establish the planned security association."),
      option("vpn-07-d", "Confirm peer reachability and required routing before tunnel testing", "Underlying IP reachability is a prerequisite to peer negotiation.")),
    sequence("vpn-07-b", "vpn-07-d", "vpn-07-c", "vpn-07-a")),
  simlet("vpn", "vpn-08", "Use the illustrative tunnel summary to choose TWO valid conclusions.",
    "Illustrative VPN summary (not device output):\nPeer: 203.0.113.9  state: established\nProtected prefixes: 10.10.0.0/16 <-> 10.40.0.0/16\nRemote-user access policy: not shown",
    four(option("vpn-08-a", "The displayed peer tunnel is established", "Correct: the summary explicitly reports established state."),
      option("vpn-08-b", "The listed protected prefixes identify the two networks in the tunnel policy", "Correct: the summary names the local and remote protected prefixes."),
      option("vpn-08-c", "Every remote user is authorized to access every internal network", "The summary explicitly says remote-user access policy is not shown."),
      option("vpn-08-d", "The tunnel guarantees that hosts in both prefixes are reachable", "An established tunnel does not by itself prove routes, filters, or endpoint reachability.")), ["vpn-08-a", "vpn-08-b"]),

  single("wireless-security", "wireless-security-01", "Which security property does WPA2-PSK primarily use the shared passphrase to provide for WLAN access?",
    four(option("wireless-security-01-a", "A shared credential for network authentication and protected link traffic", "Correct: a pre-shared key supports access authentication and derives encryption keys."),
      option("wireless-security-01-b", "Unique per-user identity from a RADIUS server", "Per-user enterprise authentication typically uses 802.1X rather than a shared PSK."),
      option("wireless-security-01-c", "A guarantee that the access point is physically secure", "Wireless credentials do not provide physical security."),
      option("wireless-security-01-d", "Automatic separation of every client into a different VLAN", "A PSK does not by itself define client VLAN assignment.")), "wireless-security-01-a"),
  single("wireless-security", "wireless-security-02", "Which WLAN authentication approach is most appropriate when users need individual credentials validated by a central service?",
    four(option("wireless-security-02-a", "WPA2/WPA3-Enterprise using 802.1X and an authentication server", "Correct: enterprise WLAN authentication can validate individual user credentials through a server such as RADIUS."),
      option("wireless-security-02-b", "An open SSID with no authentication", "An open network does not authenticate users."),
      option("wireless-security-02-c", "One shared PSK for all users", "A shared PSK does not provide individual credential validation."),
      option("wireless-security-02-d", "A hidden SSID only", "Hiding an SSID is not an authentication mechanism.")), "wireless-security-02-a"),
  single("wireless-security", "wireless-security-03", "Why is a long, unique WLAN pre-shared key preferable to a short common phrase?",
    four(option("wireless-security-03-a", "It is harder to guess or recover through offline password attacks", "Correct: stronger entropy increases resistance to guessing."),
      option("wireless-security-03-b", "It prevents radio interference", "Credential strength does not change RF interference."),
      option("wireless-security-03-c", "It makes the SSID unobservable", "The SSID remains a network identifier and is not hidden by a stronger key."),
      option("wireless-security-03-d", "It guarantees clients install security updates", "A PSK does not update client software.")), "wireless-security-03-a"),
  single("wireless-security", "wireless-security-04", "Which configuration choice best protects a guest WLAN from direct access to internal corporate services?",
    four(option("wireless-security-04-a", "Place guests in an isolated network and enforce access restrictions", "Correct: segmentation and filtering limit access beyond guest services."),
      option("wireless-security-04-b", "Reuse the corporate employee SSID and password", "Credential reuse defeats separation and broadens exposure."),
      option("wireless-security-04-c", "Disable encryption on the guest network", "Open access does not isolate guests from corporate resources."),
      option("wireless-security-04-d", "Increase the SSID beacon interval", "Beacon timing does not enforce client isolation or service access policy.")), "wireless-security-04-a"),
  multi("wireless-security", "wireless-security-05", "Which TWO practices improve WLAN security?",
    four(option("wireless-security-05-a", "Use a current supported security mode and strong credentials", "Correct: modern protection and strong credentials reduce unauthorized association risk."),
      option("wireless-security-05-b", "Treat SSID hiding as a substitute for authentication", "SSID hiding does not authenticate clients or protect data."),
      option("wireless-security-05-c", "Separate guest access from sensitive internal resources", "Correct: network segmentation reduces guest access to internal services."),
      option("wireless-security-05-d", "Share an enterprise user's individual password with all guests", "Individual credentials should not be shared broadly with guest users.")), ["wireless-security-05-a", "wireless-security-05-c"]),
  multi("wireless-security", "wireless-security-06", "Which TWO statements about shared-key and enterprise WLAN authentication are accurate?",
    four(option("wireless-security-06-a", "A PSK is shared among clients configured with that network key", "Correct: the same pre-shared credential is provisioned to the group of clients."),
      option("wireless-security-06-b", "802.1X can provide per-user or per-device authentication via a backend", "Correct: enterprise WLANs can use 802.1X/EAP with a central authentication service."),
      option("wireless-security-06-c", "An SSID name alone encrypts wireless data", "SSID is a network identifier, not an encryption key."),
      option("wireless-security-06-d", "Enterprise WLANs never need an authentication server", "Central authentication is a common part of enterprise 802.1X deployments.")), ["wireless-security-06-a", "wireless-security-06-b"]),
  ordering("wireless-security", "wireless-security-07", "Order the core steps to configure a protected employee WLAN using enterprise authentication.",
    four(option("wireless-security-07-a", "Map the WLAN to the intended employee network and apply access policy", "Network mapping and policy determine where authenticated client traffic can go."),
      option("wireless-security-07-b", "Define the SSID and intended client population", "The WLAN identity and intended users guide the security design."),
      option("wireless-security-07-c", "Configure 802.1X/EAP security and the authentication service", "Enterprise authentication must be configured before clients can authenticate."),
      option("wireless-security-07-d", "Test valid and invalid credentials and verify permitted reachability", "Validation ensures authentication and access policy both behave correctly.")),
    sequence("wireless-security-07-b", "wireless-security-07-c", "wireless-security-07-a", "wireless-security-07-d")),
  simlet("wireless-security", "wireless-security-08", "Read the illustrative WLAN profile and select TWO valid conclusions.",
    "Illustrative WLAN profile (not device output):\nSSID: StaffNet\nSecurity: WPA2-Enterprise (802.1X)\nAuthentication server: radius-a\nGuest SSID: GuestNet / isolated VLAN",
    four(option("wireless-security-08-a", "StaffNet uses enterprise authentication through the listed server", "Correct: the profile identifies WPA2-Enterprise/802.1X and radius-a."),
      option("wireless-security-08-b", "GuestNet is mapped to a VLAN described as isolated", "Correct: the profile explicitly states the guest VLAN is isolated."),
      option("wireless-security-08-c", "StaffNet uses one shared PSK", "The profile specifies enterprise 802.1X, not PSK."),
      option("wireless-security-08-d", "The output proves guest clients can reach corporate services", "Isolation is stated, and service reachability details are not provided.")), ["wireless-security-08-a", "wireless-security-08-b"]),

  single("automation", "automation-01", "What is a key operational benefit of automating a repeated network configuration task?",
    four(option("automation-01-a", "Applying a consistent, repeatable change across devices", "Correct: automation can reduce repetitive manual work and configuration variance."),
      option("automation-01-b", "Guaranteeing that every generated change is correct", "Automation can reproduce mistakes; changes still require validation."),
      option("automation-01-c", "Eliminating the need to control credentials", "Automation identities and secrets still require protection."),
      option("automation-01-d", "Making a network independent of its physical topology", "Automating tasks does not remove physical design constraints.")), "automation-01-a"),
  single("automation", "automation-02", "A team wants to reduce configuration drift among similar switches. Which approach best supports that goal?",
    four(option("automation-02-a", "Apply a reviewed common intended configuration through a repeatable process", "Correct: consistent automation helps align devices to an approved baseline."),
      option("automation-02-b", "Make undocumented manual edits on each switch", "Independent undocumented edits tend to increase drift."),
      option("automation-02-c", "Avoid checking actual device state", "Comparing actual and intended state helps identify drift."),
      option("automation-02-d", "Change device hostnames at random", "Random changes do not enforce a common configuration.")), "automation-02-a"),
  single("automation", "automation-03", "Which property makes an automation task safer to rerun after an interruption?",
    four(option("automation-03-a", "Idempotence: repeated application converges on the same desired state", "Correct: an idempotent task avoids unintended cumulative effects on rerun."),
      option("automation-03-b", "Unbounded repetition of every command", "Repeated non-idempotent commands may accumulate harmful changes."),
      option("automation-03-c", "No output or error reporting", "Suppressing feedback makes failures harder to detect."),
      option("automation-03-d", "Hard-coded credentials in the task", "Embedded secrets introduce risk and do not make reruns safe.")), "automation-03-a"),
  single("automation", "automation-04", "Before an automation job changes a production network, what is a prudent first validation step?",
    four(option("automation-04-a", "Review the intended change and test it against a representative environment or preview", "Correct: validation catches logic and impact issues before broad deployment."),
      option("automation-04-b", "Run it against every device with no review", "Immediate unreviewed deployment increases operational risk."),
      option("automation-04-c", "Disable monitoring so alerts do not appear", "Monitoring should remain available to detect unintended impact."),
      option("automation-04-d", "Remove the rollback plan", "A recovery plan is an important safeguard for production change.")), "automation-04-a"),
  multi("automation", "automation-05", "Which TWO practices support reliable network automation?",
    four(option("automation-05-a", "Use version control and peer review for automation code", "Correct: reviewed history helps find changes and catch defects."),
      option("automation-05-b", "Store production passwords in plain-text source files", "Clear-text secrets can be exposed through code and repository access."),
      option("automation-05-c", "Validate the intended result and report failures", "Correct: validation and error handling expose failed or partial changes."),
      option("automation-05-d", "Ignore device responses to keep runs fast", "Ignoring errors can leave the network in an unknown or inconsistent state.")), ["automation-05-a", "automation-05-c"]),
  multi("automation", "automation-06", "Which TWO outcomes are realistic benefits of automating routine device operations?",
    four(option("automation-06-a", "Fewer repetitive manual steps for operators", "Correct: automation can replace repeated hand-entered procedures."),
      option("automation-06-b", "No need for access controls or approval", "Automation still needs controlled identities and change governance."),
      option("automation-06-c", "More consistent execution of a defined procedure", "Correct: one maintained workflow can reduce variation among runs."),
      option("automation-06-d", "Guaranteed zero outages after any change", "Automation cannot guarantee that a change is correct or risk-free.")), ["automation-06-a", "automation-06-c"]),
  ordering("automation", "automation-07", "Order a controlled automation workflow for a routine multi-device change.",
    four(option("automation-07-a", "Run the approved change on the selected devices", "Execution follows review, testing, and authorization."),
      option("automation-07-b", "Define the desired state and target inventory", "A task needs a clear outcome and device scope."),
      option("automation-07-c", "Validate results and report exceptions", "Post-run checks determine success and identify devices needing attention."),
      option("automation-07-d", "Review and test the workflow, then obtain change approval", "Testing and approval precede production execution.")),
    sequence("automation-07-b", "automation-07-d", "automation-07-a", "automation-07-c")),
  simlet("automation", "automation-08", "Review the illustrative job summary. Which TWO conclusions are supported?",
    "Illustrative automation report (not device output):\nTask: ensure NTP server 192.0.2.40\nTargets: 12 switches\nChanged: 3  Unchanged: 8  Failed: 1\nPost-check: 11 targets report configured server",
    four(option("automation-08-a", "The run reported one target failure", "Correct: the summary gives Failed: 1."),
      option("automation-08-b", "The post-check confirmed all 12 targets", "Correct: it says 11 targets report the configured server, not all 12."),
      option("automation-08-c", "All targets were changed during this run", "Only three are listed as changed; eight were unchanged and one failed."),
      option("automation-08-d", "The task aimed to ensure the stated NTP server", "The report identifies the task as ensuring NTP server 192.0.2.40.")), ["automation-08-a", "automation-08-d"]),

  single("controllers", "controllers-01", "In software-defined networking, what is a common role of a controller?",
    four(option("controllers-01-a", "Provide centralized policy, management, or network-state coordination", "Correct: a controller can centralize network visibility and policy operations."),
      option("controllers-01-b", "Replace every forwarding device's data plane", "Controllers do not necessarily forward user packets in place of switches or routers."),
      option("controllers-01-c", "Guarantee that controller-to-device communication never fails", "Centralization does not eliminate communication or availability failures."),
      option("controllers-01-d", "Assign an IP address to every end host without any other service", "Address assignment is not the defining role of an SDN controller.")), "controllers-01-a"),
  single("controllers", "controllers-02", "Which plane is primarily responsible for forwarding user packets through a router or switch?",
    four(option("controllers-02-a", "Data plane", "Correct: the data plane performs packet or frame forwarding."),
      option("controllers-02-b", "Management plane", "The management plane supports administration and monitoring."),
      option("controllers-02-c", "Presentation plane", "Presentation is not the usual forwarding-plane term."),
      option("controllers-02-d", "Identity plane", "Identity services may inform policy but are not the forwarding plane.")), "controllers-02-a"),
  single("controllers", "controllers-03", "What is the typical purpose of a northbound API in a controller architecture?",
    four(option("controllers-03-a", "Expose controller services or abstractions to applications", "Correct: northbound interfaces commonly let applications consume controller capabilities."),
      option("controllers-03-b", "Connect an access point's radio to its antenna", "A northbound API is software integration, not a physical RF connection."),
      option("controllers-03-c", "Carry Ethernet frames between two switch ports", "Frame forwarding is not the purpose of an application-facing API."),
      option("controllers-03-d", "Replace all device operating systems", "An API does not itself replace the devices' system software.")), "controllers-03-a"),
  single("controllers", "controllers-04", "Why may a controller use southbound interfaces?",
    four(option("controllers-04-a", "To communicate with or program managed network devices", "Correct: southbound interfaces connect controller logic to the infrastructure."),
      option("controllers-04-b", "To display a dashboard to a human operator only", "A dashboard is a user interface, not the device-facing role."),
      option("controllers-04-c", "To translate JSON into human speech", "That is unrelated to the controller's device communication."),
      option("controllers-04-d", "To guarantee every device accepts every policy", "Devices may reject or fail to apply requested configuration.")), "controllers-04-a"),
  multi("controllers", "controllers-05", "Which TWO are advantages a controller-based architecture can provide?",
    four(option("controllers-05-a", "A centralized view across managed devices", "Correct: a controller can aggregate state and visibility."),
      option("controllers-05-b", "A guarantee that local device failures cannot affect service", "Central management does not prevent physical or device failures."),
      option("controllers-05-c", "Consistent policy deployment through a common management point", "Correct: centralized policy can help reduce inconsistent per-device configuration."),
      option("controllers-05-d", "Removal of the need to secure controller credentials and APIs", "Centralized control is sensitive and must be protected.")), ["controllers-05-a", "controllers-05-c"]),
  multi("controllers", "controllers-06", "Which TWO considerations should be addressed when operating a network controller?",
    four(option("controllers-06-a", "Protect controller access and its API credentials", "Correct: compromise of centralized control can have broad impact."),
      option("controllers-06-b", "Plan for controller availability and device behavior during disconnection", "Correct: operations should account for controller outages and autonomous forwarding behavior."),
      option("controllers-06-c", "Assume all device forwarding stops whenever a dashboard closes", "A user interface closing does not normally stop the forwarding plane."),
      option("controllers-06-d", "Treat controller output as infallible without validation", "Proposed changes and reported state should still be verified.")), ["controllers-06-a", "controllers-06-b"]),
  ordering("controllers", "controllers-07", "Order a safe controller-driven policy rollout.",
    four(option("controllers-07-a", "Observe device state and verify the applied policy", "Verification confirms actual results after deployment."),
      option("controllers-07-b", "Define the intended policy and target scope", "The intended outcome and scope must be explicit before deployment."),
      option("controllers-07-c", "Validate the proposed policy and resolve conflicts", "Reviewing policy catches issues before a change is pushed."),
      option("controllers-07-d", "Deploy the approved policy to the selected devices", "Deployment follows validation and approval.")),
    sequence("controllers-07-b", "controllers-07-c", "controllers-07-d", "controllers-07-a")),
  simlet("controllers", "controllers-08", "Use the illustrative controller report to select TWO supported statements.",
    "Illustrative controller report (not device output):\nPolicy campus-guest-v4: approved\nTargets: 6 access switches\nApplied: 5  Pending: 1\nLast sync: switch-6 unreachable",
    four(option("controllers-08-a", "The policy is marked approved", "Correct: the report explicitly gives the policy approved status."),
      option("controllers-08-b", "All six switches confirmed application", "The report says five applied and one is pending/unreachable."),
      option("controllers-08-c", "One target has a synchronization or reachability issue", "Correct: switch-6 is shown as unreachable and pending."),
      option("controllers-08-d", "The policy is named campus-guest-v3", "The listed policy name ends in v4.")), ["controllers-08-a", "controllers-08-c"]),

  single("ai-ml", "ai-ml-01", "How can machine learning assist network operations?",
    four(option("ai-ml-01-a", "Identify patterns or anomalies in collected telemetry", "Correct: models can help surface deviations or recurring patterns for operator review."),
      option("ai-ml-01-b", "Guarantee the cause of every outage without investigation", "Anomaly detection is not definitive root-cause proof."),
      option("ai-ml-01-c", "Replace all packet forwarding hardware", "Analysis does not replace the forwarding plane."),
      option("ai-ml-01-d", "Ensure collected data contains no sensitive information", "Machine learning does not automatically remove privacy or security risks in telemetry.")), "ai-ml-01-a"),
  single("ai-ml", "ai-ml-02", "A monitoring model flags a sudden rise in DNS errors. What is the best operational interpretation?",
    four(option("ai-ml-02-a", "Treat it as a signal to investigate and correlate with other evidence", "Correct: an alert indicates a pattern worth checking, not a proven cause."),
      option("ai-ml-02-b", "Assume the model has proven a DNS server was attacked", "An anomaly alone does not establish malicious cause."),
      option("ai-ml-02-c", "Immediately disable all DNS services", "Disabling service without validation may cause an outage and is not justified by an alert alone."),
      option("ai-ml-02-d", "Discard all telemetry from the affected site", "Removing data would eliminate evidence needed to troubleshoot.")), "ai-ml-02-a"),
  single("ai-ml", "ai-ml-03", "Why does a model trained on a historical network baseline need ongoing review?",
    four(option("ai-ml-03-a", "Normal traffic patterns can change, making a stale baseline less useful", "Correct: workloads and behavior evolve, so a model may need reassessment."),
      option("ai-ml-03-b", "Models automatically know every future network change", "A model cannot know unobserved future changes automatically."),
      option("ai-ml-03-c", "Network telemetry can never contain noise", "Telemetry may be incomplete, noisy, or affected by instrumentation changes."),
      option("ai-ml-03-d", "Review prevents all false positives by definition", "Review can improve usefulness but cannot guarantee zero false alerts.")), "ai-ml-03-a"),
  single("ai-ml", "ai-ml-04", "Which statement best describes an anomaly alert produced by an AI-assisted network tool?",
    four(option("ai-ml-04-a", "It is an indication that observed behavior differs from a learned or configured baseline", "Correct: anomaly alerts identify unusual patterns rather than establish a full explanation."),
      option("ai-ml-04-b", "It is conclusive proof of a security breach", "Unusual behavior may be benign or caused by a change; investigate before concluding."),
      option("ai-ml-04-c", "It always requires no human review", "Operators should validate important alerts using context and evidence."),
      option("ai-ml-04-d", "It guarantees that all other network metrics are healthy", "One signal says nothing conclusive about unrelated metrics.")), "ai-ml-04-a"),
  multi("ai-ml", "ai-ml-05", "Which TWO practices make AI-assisted network alerting more useful and responsible?",
    four(option("ai-ml-05-a", "Correlate alerts with topology, change records, and other telemetry", "Correct: context helps distinguish relevant incidents from benign variation."),
      option("ai-ml-05-b", "Automatically treat every anomaly as malicious", "An anomaly can have benign causes and should not be equated with an attack."),
      option("ai-ml-05-c", "Review alert quality and account for data quality or bias", "Correct: poor input quality or bias can produce misleading conclusions."),
      option("ai-ml-05-d", "Collect unrestricted personal data whether needed or not", "Data collection should be appropriate, minimized, and governed.")), ["ai-ml-05-a", "ai-ml-05-c"]),
  multi("ai-ml", "ai-ml-06", "Which TWO are plausible machine-learning uses in network operations?",
    four(option("ai-ml-06-a", "Detect a traffic-volume pattern that deviates from its usual baseline", "Correct: baseline comparison can surface unusual traffic behavior."),
      option("ai-ml-06-b", "Predict with certainty which physical cable will fail next", "Predictions are probabilistic and cannot guarantee an exact future failure."),
      option("ai-ml-06-c", "Group related events to help prioritize troubleshooting", "Correct: analytics can correlate event patterns and reduce triage effort."),
      option("ai-ml-06-d", "Replace the need to confirm a proposed remediation", "Recommendations still require validation and appropriate change control.")), ["ai-ml-06-a", "ai-ml-06-c"]),
  ordering("ai-ml", "ai-ml-07", "Order a sensible workflow for responding to an AI-generated network anomaly alert.",
    four(option("ai-ml-07-a", "Apply an approved remediation if evidence supports it", "A change should follow validation and normal authorization."),
      option("ai-ml-07-b", "Review the alert and relevant underlying telemetry", "Start by examining what the tool actually observed."),
      option("ai-ml-07-c", "Correlate with changes, topology, and independent signals", "Context helps test possible explanations."),
      option("ai-ml-07-d", "Validate the result and provide feedback on the alert", "Post-action checks and feedback support operations and model quality.")),
    sequence("ai-ml-07-b", "ai-ml-07-c", "ai-ml-07-a", "ai-ml-07-d")),
  simlet("ai-ml", "ai-ml-08", "Review the illustrative analytics summary and select TWO conclusions that it supports.",
    "Illustrative analytics summary (not device output):\nMetric: DNS timeout rate\nBaseline: 0.4% (previous 14-day median)\nObserved: 4.8% for 6 minutes\nModel label: anomalous; confidence: medium",
    four(option("ai-ml-08-a", "The observed timeout rate is above the displayed baseline", "Correct: 4.8% is greater than the 0.4% baseline."),
      option("ai-ml-08-b", "The summary proves a DNS attack is in progress", "An anomaly label with medium confidence does not identify a cause."),
      option("ai-ml-08-c", "The tool labeled the measurement anomalous with medium confidence", "Correct: both the label and confidence are stated."),
      option("ai-ml-08-d", "The baseline is a 14-day maximum", "It is specifically identified as a 14-day median.")), ["ai-ml-08-a", "ai-ml-08-c"]),

  single("rest-apis", "rest-apis-01", "Which HTTP method is conventionally used to retrieve a resource without requesting a change?",
    four(option("rest-apis-01-a", "GET", "Correct: GET requests representation of a resource."),
      option("rest-apis-01-b", "DELETE", "DELETE requests removal of a resource."),
      option("rest-apis-01-c", "PATCH", "PATCH requests a partial modification."),
      option("rest-apis-01-d", "POST", "POST commonly submits data or requests a subordinate action, not a simple read.")), "rest-apis-01-a"),
  single("rest-apis", "rest-apis-02", "What does an HTTP 404 response normally indicate for an API request?",
    four(option("rest-apis-02-a", "The requested resource was not found", "Correct: 404 indicates that the server could not find the requested resource."),
      option("rest-apis-02-b", "The request succeeded with no content", "204 is the conventional No Content success status."),
      option("rest-apis-02-c", "The client is authenticated successfully", "Authentication success is not what 404 denotes."),
      option("rest-apis-02-d", "The server has accepted a queued request", "202 is commonly used for an accepted asynchronous request.")), "rest-apis-02-a"),
  single("rest-apis", "rest-apis-03", "Which HTTP method is generally intended to remove a resource identified by its URI?",
    four(option("rest-apis-03-a", "DELETE", "Correct: DELETE requests removal of the identified resource."),
      option("rest-apis-03-b", "GET", "GET retrieves a representation and should not be used to delete a resource."),
      option("rest-apis-03-c", "HEAD", "HEAD retrieves response metadata without the representation."),
      option("rest-apis-03-d", "OPTIONS", "OPTIONS describes supported communication options.")), "rest-apis-03-a"),
  single("rest-apis", "rest-apis-04", "Why should a client check an API response's status code before treating its body as successful data?",
    four(option("rest-apis-04-a", "The status communicates the outcome, such as success, client error, or server error", "Correct: a response body alone may not indicate whether the request succeeded."),
      option("rest-apis-04-b", "Status codes contain the entire response data", "Resource data is usually in headers or body, not encoded entirely in the status."),
      option("rest-apis-04-c", "All HTTP status codes mean the same thing", "Status classes communicate materially different outcomes."),
      option("rest-apis-04-d", "A status code encrypts the response", "HTTP status does not provide encryption.")), "rest-apis-04-a"),
  multi("rest-apis", "rest-apis-05", "Which TWO practices improve the security of a network-management REST API client?",
    four(option("rest-apis-05-a", "Use HTTPS and validate the server identity", "Correct: TLS protects transport and certificate validation helps detect impersonation."),
      option("rest-apis-05-b", "Embed a permanent administrator token in public source code", "Public, long-lived credentials can be copied and abused."),
      option("rest-apis-05-c", "Use scoped credentials and protect them outside source code", "Correct: least-privilege credentials and secure secret handling reduce exposure."),
      option("rest-apis-05-d", "Disable all authorization checks for ease of testing", "Removing authorization exposes protected API operations.")), ["rest-apis-05-a", "rest-apis-05-c"]),
  multi("rest-apis", "rest-apis-06", "Which TWO statements about common REST API request components are accurate?",
    four(option("rest-apis-06-a", "The URI identifies the target resource or endpoint", "Correct: the request URI locates the resource being addressed."),
      option("rest-apis-06-b", "The HTTP method indicates an operation such as retrieval or modification", "Correct: methods convey the requested operation semantics."),
      option("rest-apis-06-c", "A JSON body is mandatory for every GET request", "GET requests commonly have no body; it is not universally required."),
      option("rest-apis-06-d", "HTTP headers can never carry content-type information", "Content-Type is commonly expressed in a request or response header.")), ["rest-apis-06-a", "rest-apis-06-b"]),
  ordering("rest-apis", "rest-apis-07", "Order a client workflow for safely reading interface status from an API.",
    four(option("rest-apis-07-a", "Parse the response only after checking its status", "Status evaluation distinguishes successful results from errors."),
      option("rest-apis-07-b", "Authenticate securely and prepare the resource URI", "A client needs an authorized connection and the correct endpoint."),
      option("rest-apis-07-c", "Send the GET request over the protected connection", "The request retrieves the resource without intending a change."),
      option("rest-apis-07-d", "Handle errors and validate the returned data", "Data validation and error handling complete a reliable read.")),
    sequence("rest-apis-07-b", "rest-apis-07-c", "rest-apis-07-a", "rest-apis-07-d")),
  simlet("rest-apis", "rest-apis-08", "Use the illustrative API exchange to identify TWO correct interpretations.",
    "Illustrative API exchange (not device output):\nGET /api/v1/interfaces/eth0\nHTTP/1.1 200 OK\nContent-Type: application/json\n{\"name\":\"eth0\",\"adminStatus\":\"up\"}",
    four(option("rest-apis-08-a", "The GET request received a successful 200 response", "Correct: 200 OK indicates the request succeeded."),
      option("rest-apis-08-b", "The response body says eth0 has adminStatus up", "Correct: the JSON object lists that interface and status."),
      option("rest-apis-08-c", "The request deleted the interface resource", "GET is a retrieval method, and the response is successful."),
      option("rest-apis-08-d", "The response content type is XML", "The Content-Type header explicitly identifies application/json.")), ["rest-apis-08-a", "rest-apis-08-b"]),

  single("json", "json-01", "In JSON, which structure represents an unordered collection of key-value pairs?",
    four(option("json-01-a", "Object", "Correct: a JSON object contains name/value pairs inside braces."),
      option("json-01-b", "Array", "An array is an ordered list of values."),
      option("json-01-c", "String", "A string is a single text value."),
      option("json-01-d", "Boolean", "A boolean is the literal true or false.")), "json-01-a"),
  single("json", "json-02", "Which JSON value type is used for an ordered list of values?",
    four(option("json-02-a", "Array", "Correct: JSON arrays preserve element order and use square brackets."),
      option("json-02-b", "Object", "An object organizes key-value pairs rather than being a list."),
      option("json-02-c", "Number", "A number is one numeric value."),
      option("json-02-d", "Null", "Null represents the absence of a value.")), "json-02-a"),
  single("json", "json-03", "Which literal is a valid JSON boolean value?",
    four(option("json-03-a", "false", "Correct: JSON boolean literals are lowercase true and false."),
      option("json-03-b", "False", "JSON literals are case-sensitive; False is not valid JSON."),
      option("json-03-c", "\"false\"", "Quoted false is a string, not a boolean value."),
      option("json-03-d", "0", "Zero is a number, not a boolean literal.")), "json-03-a"),
  single("json", "json-04", "Which text is valid JSON for an object with an interface name and an up boolean state?",
    four(option("json-04-a", "{\"name\":\"eth1\",\"up\":true}", "Correct: keys and strings are quoted, and true is a valid unquoted boolean."),
      option("json-04-b", "{name:\"eth1\",up:true}", "JSON requires quoted object keys."),
      option("json-04-c", "{\"name\":\"eth1\",\"up\":True}", "The JSON boolean literal must be lowercase true."),
      option("json-04-d", "{\"name\":\"eth1\",}", "A trailing comma is not valid in standard JSON.")), "json-04-a"),
  multi("json", "json-05", "Which TWO statements about JSON syntax are correct?",
    four(option("json-05-a", "Object member names are strings enclosed in double quotes", "Correct: JSON object keys must be quoted strings."),
      option("json-05-b", "Single quotes are interchangeable with double quotes for JSON strings", "JSON strings require double quotes."),
      option("json-05-c", "An array can contain values of different JSON types", "Correct: arrays can contain strings, numbers, objects, arrays, booleans, or null."),
      option("json-05-d", "A JSON number must always be enclosed in quotation marks", "Numbers are represented as numeric values without quotes.")), ["json-05-a", "json-05-c"]),
  multi("json", "json-06", "Which TWO values are valid JSON values?",
    four(option("json-06-a", "null", "Correct: null is a valid lowercase JSON literal."),
      option("json-06-b", "undefined", "Undefined is not a JSON value."),
      option("json-06-c", "true", "Correct: true is a valid lowercase JSON boolean literal."),
      option("json-06-d", "NaN", "NaN is not a standard JSON number or literal.")), ["json-06-a", "json-06-c"]),
  ordering("json", "json-07", "Order the conceptual steps for consuming a JSON API response as structured data.",
    four(option("json-07-a", "Access fields and validate their types and expected values", "Type and value checks ensure the data suits the application."),
      option("json-07-b", "Obtain the response body", "The client must first receive the body."),
      option("json-07-c", "Parse the JSON text into structured values", "Parsing turns serialized JSON into objects, arrays, and primitives."),
      option("json-07-d", "Handle parsing or schema errors safely", "The client must handle malformed or unexpected input rather than assuming success.")),
    sequence("json-07-b", "json-07-c", "json-07-a", "json-07-d")),
  simlet("json", "json-08", "Read the illustrative JSON response and select TWO accurate statements.",
    "Illustrative JSON (not device output):\n{\"device\":\"sw-a\",\"interfaces\":[{\"name\":\"Gi1/0/1\",\"up\":true},{\"name\":\"Gi1/0/2\",\"up\":false}],\"count\":2}",
    four(option("json-08-a", "interfaces is an array containing two objects", "Correct: the array has two object elements."),
      option("json-08-b", "count is a JSON string containing the character 2", "The value 2 is unquoted, so it is a number."),
      option("json-08-c", "The Gi1/0/1 object's up value is the boolean true", "Correct: up is an unquoted lowercase JSON boolean."),
      option("json-08-d", "The document contains a top-level JSON array", "The outermost structure is an object enclosed by braces.")), ["json-08-a", "json-08-c"]),

  single("config-tools", "config-tools-01", "What is a typical purpose of an Ansible playbook in network operations?",
    four(option("config-tools-01-a", "Describe repeatable tasks to apply to selected managed hosts", "Correct: a playbook organizes tasks and target hosts for automated execution."),
      option("config-tools-01-b", "Physically connect switch ports with patch cables", "Software tools do not make physical cable connections."),
      option("config-tools-01-c", "Replace all device authentication", "Playbooks still need authorized access to managed systems."),
      option("config-tools-01-d", "Guarantee an API service has no defects", "Configuration tools do not guarantee the correctness of every external service.")), "config-tools-01-a"),
  single("config-tools", "config-tools-02", "In infrastructure-as-code workflows, what is the purpose of a plan or preview stage?",
    four(option("config-tools-02-a", "Show proposed changes before applying them", "Correct: reviewing a plan helps identify unintended resource changes before execution."),
      option("config-tools-02-b", "Delete the need for state or inventory", "Planning does not remove the need to track infrastructure or targets."),
      option("config-tools-02-c", "Apply every change without operator visibility", "A preview exists to expose proposed changes, not hide them."),
      option("config-tools-02-d", "Encrypt every resource automatically", "A preview stage does not itself encrypt infrastructure.")), "config-tools-02-a"),
  single("config-tools", "config-tools-03", "Why should configuration automation use an inventory or explicit target list?",
    four(option("config-tools-03-a", "To define which managed devices are in scope", "Correct: target selection limits execution to intended devices."),
      option("config-tools-03-b", "To convert every device into a controller", "Inventory describes targets; it does not change their architecture."),
      option("config-tools-03-c", "To guarantee that unreachable devices are configured", "A target list cannot guarantee connectivity or successful execution."),
      option("config-tools-03-d", "To store clear-text passwords for all users", "Credentials should be protected separately, not embedded as exposed inventory data.")), "config-tools-03-a"),
  single("config-tools", "config-tools-04", "What does idempotent behavior mean for a configuration-management task?",
    four(option("config-tools-04-a", "Applying it repeatedly leaves the system in the same intended state", "Correct: reruns converge on the declared state without adding duplicate changes."),
      option("config-tools-04-b", "The task always changes the device on every run", "Repeated changes are generally not idempotent."),
      option("config-tools-04-c", "The task cannot fail", "Idempotence does not prevent failures such as authentication or connectivity errors."),
      option("config-tools-04-d", "The task runs without a target inventory", "Idempotence concerns effects, not target selection.")), "config-tools-04-a"),
  multi("config-tools", "config-tools-05", "Which TWO practices reduce risk when using configuration-management tools?",
    four(option("config-tools-05-a", "Review proposed changes and use a limited test scope first", "Correct: previews and staged deployment reduce the chance of broad unintended impact."),
      option("config-tools-05-b", "Disable logs so failures are not visible", "Logs support troubleshooting and auditability."),
      option("config-tools-05-c", "Protect credentials and grant the automation identity only necessary access", "Correct: secret protection and least privilege reduce the impact of compromise."),
      option("config-tools-05-d", "Run every playbook as a global administrator without review", "Excessive privileges and lack of review increase risk.")), ["config-tools-05-a", "config-tools-05-c"]),
  multi("config-tools", "config-tools-06", "Which TWO distinctions between configuration-management and provisioning tools are generally useful?",
    four(option("config-tools-06-a", "Configuration management commonly enforces intended settings on managed systems", "Correct: tools can repeatedly apply configuration to existing hosts."),
      option("config-tools-06-b", "Provisioning tools can create or manage infrastructure resources", "Correct: infrastructure tools can describe and provision resources such as networks or instances."),
      option("config-tools-06-c", "Neither type benefits from version control", "Version control helps track intended changes for both."),
      option("config-tools-06-d", "Both guarantee that any declared plan is safe to apply", "Plans still need review; tools cannot guarantee every change is safe.")), ["config-tools-06-a", "config-tools-06-b"]),
  ordering("config-tools", "config-tools-07", "Order a controlled configuration-management run for a production device group.",
    four(option("config-tools-07-a", "Apply the approved change to the intended inventory", "The production run occurs after scope and change approval."),
      option("config-tools-07-b", "Define desired settings and select the target inventory", "The tool needs a target scope and intended state."),
      option("config-tools-07-c", "Review a preview, test, and obtain authorization", "Review and approval should precede production execution."),
      option("config-tools-07-d", "Verify device state and record results or failures", "Post-run validation confirms outcomes and captures exceptions.")),
    sequence("config-tools-07-b", "config-tools-07-c", "config-tools-07-a", "config-tools-07-d")),
  simlet("config-tools", "config-tools-08", "Use the illustrative configuration-tool run report. Select TWO supported conclusions.",
    "Illustrative tool report (not device output):\nPlay: enforce NTP\nInventory: edge-switches (5 hosts)\nChanged: edge-1, edge-3\nOK unchanged: edge-2, edge-4\nUnreachable: edge-5",
    four(option("config-tools-08-a", "Two reachable devices were changed", "Correct: edge-1 and edge-3 are listed as changed."),
      option("config-tools-08-b", "All five hosts completed successfully", "edge-5 is listed as unreachable, so not all hosts completed."),
      option("config-tools-08-c", "Two listed devices were already compliant and unchanged", "Correct: edge-2 and edge-4 are marked OK unchanged."),
      option("config-tools-08-d", "The play was intended to configure DNS", "The report names the play enforce NTP.")), ["config-tools-08-a", "config-tools-08-c"]),

  single("dna-center", "dna-center-01", "What is a common role of Cisco DNA Center in a managed campus network?",
    four(option("dna-center-01-a", "Centralized network management, automation, and assurance workflows", "Correct: the platform supports centralized management and operational workflows."),
      option("dna-center-01-b", "Replacing Ethernet switches as the physical forwarding fabric", "DNA Center manages infrastructure; it does not physically replace the switches."),
      option("dna-center-01-c", "Providing public DNS resolution for every client", "DNS service is not the platform's defining role."),
      option("dna-center-01-d", "Encrypting all internet traffic without network devices", "The platform does not independently provide universal traffic encryption.")), "dna-center-01-a"),
  single("dna-center", "dna-center-02", "In SD-Access, what is a high-level benefit of using a fabric architecture?",
    four(option("dna-center-02-a", "Consistent, policy-driven segmentation across the campus fabric", "Correct: fabric policy can help apply segmentation consistently across managed access."),
      option("dna-center-02-b", "Eliminating the need for any IP addressing", "Fabric networks still use IP addressing."),
      option("dna-center-02-c", "Removing all wired links between access devices", "SD-Access is a logical architecture and does not eliminate physical links."),
      option("dna-center-02-d", "Allowing every endpoint to bypass network policy", "Fabric policy is intended to enforce access intent, not bypass it.")), "dna-center-02-a"),
  single("dna-center", "dna-center-03", "What is the purpose of a virtual network in an SD-Access design?",
    four(option("dna-center-03-a", "Provide a logical segmentation boundary for groups of users or services", "Correct: virtual networks support macro-segmentation within the fabric."),
      option("dna-center-03-b", "Replace the physical campus cabling plant", "Virtual networks are logical constructs and do not replace cabling."),
      option("dna-center-03-c", "Assign a unique public IP address to every endpoint", "A virtual network does not imply globally unique public addressing."),
      option("dna-center-03-d", "Disable authentication for endpoints", "Network segmentation does not remove the need for identity and access policy.")), "dna-center-03-a"),
  single("dna-center", "dna-center-04", "What does network assurance help an operator do?",
    four(option("dna-center-04-a", "Observe network health and investigate issues using collected operational data", "Correct: assurance capabilities provide visibility that can support troubleshooting."),
      option("dna-center-04-b", "Guarantee that no network incident can occur", "Monitoring can improve detection but cannot guarantee incident-free operation."),
      option("dna-center-04-c", "Replace every change-approval process", "Assurance visibility does not replace operational change governance."),
      option("dna-center-04-d", "Configure client applications without any network context", "Assurance concerns infrastructure and its operational state.")), "dna-center-04-a"),
  multi("dna-center", "dna-center-05", "Which TWO are appropriate uses of a centralized campus-management platform?",
    four(option("dna-center-05-a", "Automate approved provisioning workflows for managed infrastructure", "Correct: centralized workflows can help provision devices consistently."),
      option("dna-center-05-b", "Assume a centrally pushed change cannot affect service", "Centralized changes can still cause impact and need review and validation."),
      option("dna-center-05-c", "Use collected telemetry to assist health monitoring and troubleshooting", "Correct: operational data can support assurance and fault investigation."),
      option("dna-center-05-d", "Store unrestricted administrator secrets in user-facing dashboards", "Administrative credentials must be protected, not exposed in dashboards.")), ["dna-center-05-a", "dna-center-05-c"]),
  multi("dna-center", "dna-center-06", "Which TWO statements about SD-Access segmentation are accurate at a high level?",
    four(option("dna-center-06-a", "Virtual networks can provide macro-segmentation between traffic groups", "Correct: virtual networks separate broad groups within the fabric."),
      option("dna-center-06-b", "Segmentation makes access policy and endpoint identity irrelevant", "Segmentation is part of policy design; identity and access controls remain relevant."),
      option("dna-center-06-c", "Policy can be managed centrally and applied across fabric infrastructure", "Correct: centralized management can support consistent policy application."),
      option("dna-center-06-d", "Every endpoint must be connected directly to the controller", "Endpoints connect through the network fabric; they do not each require a direct controller link.")), ["dna-center-06-a", "dna-center-06-c"]),
  ordering("dna-center", "dna-center-07", "Order a high-level workflow to onboard a managed campus switch through a centralized platform.",
    four(option("dna-center-07-a", "Assign the intended site, device role, and approved configuration", "The device needs the correct organizational context and intended settings."),
      option("dna-center-07-b", "Discover or add the device and verify reachability and credentials", "The platform must identify and communicate with the device before provisioning."),
      option("dna-center-07-c", "Validate the resulting configuration and operational health", "Post-provision checks confirm successful onboarding."),
      option("dna-center-07-d", "Authorize and run the planned provisioning workflow", "The approved workflow applies the assigned intent.")),
    sequence("dna-center-07-b", "dna-center-07-a", "dna-center-07-d", "dna-center-07-c")),
  simlet("dna-center", "dna-center-08", "Read the illustrative management summary and select TWO conclusions it supports.",
    "Illustrative campus summary (not device output):\nSite: Building-A\nProvisioning: 9 devices complete, 1 device pending\nAssurance: 1 access switch reports elevated client onboarding failures\nFabric virtual network: Corp-Users",
    four(option("dna-center-08-a", "One device has not completed provisioning", "Correct: the summary reports one device pending."),
      option("dna-center-08-b", "All access switches have healthy client onboarding", "The report says one switch has elevated onboarding failures."),
      option("dna-center-08-c", "The fabric virtual network shown is Corp-Users", "Correct: that is the listed virtual network."),
      option("dna-center-08-d", "Ten devices completed provisioning", "Nine are complete and one is pending.")), ["dna-center-08-a", "dna-center-08-c"])
];

export const ccnaSecurityAutomationQuestions: AssessmentQuestion[] = questions;
