export type LessonContent = {
  learningObjectives: string[];
  deepDive: string[];
  diagram: { caption: string; nodes: { title: string; subtitle: string }[] };
  lab: {
    title: string;
    scenario: string;
    steps: string[];
    check: string;
    choices: [string, string, string, string];
    answer: number;
    explanation: string;
    command?: string;
  };
};

const lesson = (
  learningObjectives: string[],
  deepDive: string[],
  diagram: LessonContent["diagram"],
  lab: LessonContent["lab"]
): LessonContent => ({ learningObjectives, deepDive, diagram, lab });

export const lessonContent: Record<string, LessonContent> = {
  "network-devices": lesson(
    ["Distinguish the forwarding roles of routers, switches, and access points.", "Trace how a host reaches a remote IP network."],
    ["A Layer 2 switch forwards Ethernet frames within a VLAN by learning source MAC addresses and consulting its MAC address table. It does not normally choose a path between IP networks.", "A router examines the destination IP address, looks up a matching route, and forwards the packet toward a next hop. Each routed interface belongs to a different IP subnet.", "An access point bridges wireless clients into a wired LAN; it is not automatically a router. A typical path is client radio, AP, switch, default gateway, then the routed destination."],
    { caption: "A client moves from wireless access to a routed destination.", nodes: [{ title: "Client", subtitle: "Creates an IP packet" }, { title: "Access point", subtitle: "Bridges wireless to LAN" }, { title: "Switch", subtitle: "Forwards within VLAN" }, { title: "Router", subtitle: "Routes between IP networks" }] },
    { title: "Trace a remote connection", scenario: "A laptop on a WLAN opens a service hosted in another subnet.", steps: ["Identify the client's access medium and the device bridging it to the LAN.", "Follow the frame through the local VLAN to the configured default gateway.", "At the router, use the destination prefix to choose the outgoing path."], check: "Which device makes the Layer 3 forwarding decision for the remote subnet?", choices: ["The access point radio", "The Layer 2 switch MAC table", "The router routing table", "The DNS resolver"], answer: 2, explanation: "The router uses its IP routing table to select an outgoing interface or next hop for a different network." }
  ),
  "topologies": lesson(
    ["Compare star, mesh, hierarchical, and spine-and-leaf designs.", "Relate redundancy and failure scope to physical and logical topology."],
    ["A topology describes how devices and links are arranged. In a star, endpoints attach to a central switch, making management straightforward but making that central device important.", "A mesh adds alternate paths; full mesh grows rapidly in link count, while partial mesh connects only selected nodes. Redundancy improves resilience but introduces more design and loop-control requirements.", "Enterprise campus designs commonly separate access, distribution, and core roles; smaller sites may collapse layers. Spine-and-leaf gives each leaf a path to every spine and supports predictable data-center east-west traffic."],
    { caption: "A resilient hierarchical campus path.", nodes: [{ title: "Endpoints", subtitle: "Access layer" }, { title: "Access switches", subtitle: "Connect users and APs" }, { title: "Distribution", subtitle: "Policy and aggregation" }, { title: "Core", subtitle: "Fast campus transit" }] },
    { title: "Select a topology", scenario: "A small office needs simple wiring and wants one endpoint cable failure not to affect neighbors.", steps: ["List the endpoints and central switching location.", "Choose a layout that isolates an individual access-link failure.", "Identify the remaining single points of failure for a later resilience plan."], check: "Which topology best matches the stated simple-office requirement?", choices: ["A star with endpoints on a central switch", "A bus with all endpoints on one shared cable", "A full mesh between every endpoint", "A ring with all users inline"], answer: 0, explanation: "A star connects each endpoint independently to a central switch, so one endpoint cable failure is generally localized. The central switch itself can still be a failure point." }
  ),
  "cabling": lesson(
    ["Choose copper or fiber based on distance, speed, and environment.", "Recognize common Ethernet media and transceiver considerations."],
    ["Twisted-pair copper Ethernet is common for endpoint access and carries electrical signals. Link distance and category rating constrain supported rates; standard structured cabling channels are typically limited to 100 m.", "Fiber carries light and supports longer distances or high bandwidth, with multimode and single-mode variants suited to different optics and reach. Both ends must use compatible fiber type, wavelength, and transceivers.", "A physical link requires compatible connectors, pinout, speed capabilities, and an operational interface. Use the approved media specification rather than assuming that a connector which fits is appropriate."],
    { caption: "Select a medium to fit the path.", nodes: [{ title: "Endpoint", subtitle: "Copper for typical short drop" }, { title: "Access switch", subtitle: "Electrical or optical port" }, { title: "Building uplink", subtitle: "Fiber for longer reach" }, { title: "Remote switch", subtitle: "Compatible optic required" }] },
    { title: "Choose an uplink medium", scenario: "Two wiring closets are separated by a long inter-building path.", steps: ["Estimate the link distance and required capacity.", "Check the ports and approved transceivers at both ends.", "Select matching fiber type and optics, then verify link status."], check: "What must match across an optical link?", choices: ["Only the device hostnames", "Fiber/optic characteristics and compatible interfaces at both ends", "The VLAN numbers on endpoint ports", "The DNS search domain"], answer: 1, explanation: "Optics, wavelength, fiber type, connector, and supported reach must be compatible at both ends; VLAN configuration does not make mismatched physical media work." }
  ),
  "interface-errors": lesson(
    ["Interpret interface status and common physical error counters.", "Use a layered troubleshooting sequence to isolate link faults."],
    ["A down/down interface often suggests no physical signal or a disabled peer; an administratively down state means the local interface has been shut. Always distinguish local configuration from cable or remote-end problems.", "CRC/FCS errors indicate frames failed integrity checks and often point to damaged cabling, interference, or a faulty interface. Collisions and late collisions can indicate duplex problems on legacy half-duplex links.", "Counters are evidence over time, not a diagnosis by themselves. Clear or note a baseline, observe whether counters rise, inspect both ends and the cable path, and change one controlled variable at a time."],
    { caption: "Troubleshoot from physical link toward service.", nodes: [{ title: "Interface state", subtitle: "Admin and operational status" }, { title: "Media", subtitle: "Cable, optic, seating" }, { title: "Counters", subtitle: "CRC, drops, speed/duplex" }, { title: "Service test", subtitle: "Verify application path" }] },
    { title: "Investigate rising CRC errors", scenario: "A switch port is up, but CRC errors increase during a file copy.", steps: ["Record the interface status, speed, duplex, and current error counters.", "Inspect/reseat or replace the patch lead and check the peer interface.", "Retest and compare counter deltas before escalating to hardware."], check: "Which next action most directly tests a likely physical cause?", choices: ["Change the host DNS server", "Replace or reseat the cable and observe new CRC counts", "Add a default route", "Change the SSID"], answer: 1, explanation: "CRC errors implicate frame integrity on the physical link, so checking cable condition and whether errors continue is a targeted test.", command: "show interfaces"}
  ),
  "tcp-udp": lesson(
    ["Explain TCP reliability and connection state.", "Choose when UDP's lower protocol overhead is useful."],
    ["TCP establishes a connection, numbers bytes, acknowledges received data, retransmits missing data, and presents an ordered byte stream to an application. This control improves reliability but can add delay.", "UDP sends datagrams without TCP's connection setup or built-in retransmission and ordering. Applications can add their own reliability when needed, or prefer timely delivery over waiting for lost packets.", "Neither transport is inherently secure; encryption and authentication are separate concerns such as TLS or a secure application protocol. TCP and UDP both use port numbers to identify application endpoints."],
    { caption: "Transport behavior shapes application delivery.", nodes: [{ title: "Application", subtitle: "Chooses service behavior" }, { title: "TCP", subtitle: "Ordered, acknowledged stream" }, { title: "UDP", subtitle: "Datagrams, low overhead" }, { title: "IP network", subtitle: "Best-effort packet delivery" }] },
    { title: "Match transport to traffic", scenario: "A real-time voice application should avoid waiting for retransmission of stale audio.", steps: ["Identify whether freshness or perfect delivery is the primary requirement.", "Choose a transport and note where any recovery responsibility belongs.", "Allow only the required transport and application ports in the path."], check: "Which transport commonly suits interactive voice media?", choices: ["TCP, because it retransmits every delayed packet", "UDP, because the application can favor timely datagrams", "ARP, because it has port numbers", "ICMP, because it encrypts voice"], answer: 1, explanation: "UDP avoids TCP's ordered retransmission behavior; real-time applications can tolerate occasional loss and prioritize low delay. UDP itself does not guarantee delivery."}
  ),
  "ipv4-subnetting": lesson(
    ["Calculate network, broadcast, and host ranges from an IPv4 prefix.", "Distinguish total addresses from traditionally usable host addresses."],
    ["An IPv4 address has 32 bits. A prefix length identifies the network bits; the remaining host bits determine addresses within that subnet. A /26 leaves six host bits, or 64 total addresses.", "For ordinary multi-access IPv4 subnets, the all-zero host address identifies the network and the all-one host address is the directed broadcast, leaving 62 traditionally usable host addresses in a /26. Point-to-point and special prefixes can have different usable-address conventions.", "A /31 is specifically useful on point-to-point links under RFC 3021, where both addresses may be used as endpoints and there is no directed broadcast in the usual sense. A /32 represents one host route; do not apply the common subtract-two shortcut blindly."],
    { caption: "A /26 divides into network, hosts, and broadcast.", nodes: [{ title: "192.0.2.64", subtitle: "Network address" }, { title: ".65 - .126", subtitle: "62 conventional host addresses" }, { title: "192.0.2.127", subtitle: "Directed broadcast" }] },
    { title: "Plan an IPv4 subnet", scenario: "A lab needs a conventional LAN for up to 50 hosts using 192.0.2.64/26.", steps: ["Count the host bits and total addresses in the /26.", "Exclude the network and directed broadcast for a conventional LAN.", "Assign host addresses only within the resulting usable range."], check: "How many traditionally usable host addresses does this /26 provide?", choices: ["30", "62", "64", "126"], answer: 1, explanation: "A /26 leaves six host bits: 2^6 = 64 total addresses; for a conventional subnet subtract the network and broadcast addresses, yielding 62."}
  ),
  "private-ipv4": lesson(
    ["Identify the three RFC 1918 private IPv4 blocks.", "Explain why private addressing usually needs translation or another edge service for internet access."],
    ["RFC 1918 reserves 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16 for private internetworks. The 172 range is only 172.16.0.0 through 172.31.255.255; not all 172 addresses are private.", "Private addresses can be reused by unrelated organizations and are not globally routed on the public internet. An organization commonly translates private source addresses at an edge, but NAT is not the same thing as encryption or a security policy.", "A private address still requires correct subnetting, gateway, and route handling inside the enterprise. Overlapping private blocks can complicate mergers, VPNs, and inter-site routing."],
    { caption: "Private hosts reach public services through an edge boundary.", nodes: [{ title: "RFC 1918 host", subtitle: "Private source address" }, { title: "Internal router", subtitle: "Routes within enterprise" }, { title: "NAT edge", subtitle: "Translates as designed" }, { title: "Public network", subtitle: "Globally routed destination" }] },
    { title: "Classify a private address", scenario: "An engineer reviews the address 172.20.4.9 and asks whether it is in an RFC 1918 block.", steps: ["Compare the first octets against each RFC 1918 range.", "Confirm the address is in 172.16.0.0/12, not merely somewhere in 172/8.", "Explain how a private host can obtain external reachability at an edge."], check: "Is 172.20.4.9 RFC 1918 private space?", choices: ["Yes, it is within 172.16.0.0/12", "No, only 10/8 is private", "No, every 172 address is public", "Yes, because all IPv4 addresses ending in .9 are private"], answer: 0, explanation: "172.20.4.9 lies between 172.16.0.0 and 172.31.255.255, the RFC 1918 172.16.0.0/12 block."}
  ),
  "ipv6-addressing": lesson(
    ["Recognize common IPv6 address scopes and formats.", "Apply zero compression and explain the /64 subnet convention."],
    ["IPv6 addresses contain 128 bits written as eight hexadecimal groups. Leading zeroes in a group can be omitted, and one run of consecutive zero groups may be compressed once with ::.", "Global unicast is globally scoped addressing; link-local FE80::/10 is used on a link and is not forwarded by routers. Unique local FC00::/7 is intended for private-like internal use, while multicast replaces IPv4 broadcast behavior.", "Many LANs use a /64 prefix, leaving 64 interface-identifier bits, though designs can use other lengths in specific contexts. IPv6 has no broadcast address; all-nodes or solicited-node multicast serves related functions."],
    { caption: "IPv6 scope determines where a destination is meaningful.", nodes: [{ title: "Link-local", subtitle: "FE80::/10, one link" }, { title: "Unique local", subtitle: "FC00::/7, internal scope" }, { title: "Global unicast", subtitle: "Routable prefix" }, { title: "Multicast", subtitle: "One-to-many delivery" }] },
    { title: "Choose an IPv6 address scope", scenario: "A router needs a next-hop address for a directly connected IPv6 neighbor.", steps: ["Check that the address is reachable on the local link.", "When using a link-local next hop, identify the outgoing interface as well.", "Do not attempt to route that link-local address through a remote router."], check: "Why does a link-local next hop need an interface context?", choices: ["Link-local addresses are reused on different links and are not globally routed", "IPv6 has no routing table", "A link-local address is a DNS name", "The prefix is always /128"], answer: 0, explanation: "A FE80::/10 address is valid only on its local link and can occur on multiple links, so an interface scope disambiguates it."}
  ),
  "client-ip-config": lesson(
    ["Identify the address, prefix/mask, gateway, and DNS settings a host needs.", "Use host configuration evidence to distinguish local and remote reachability failures."],
    ["A usable host configuration includes an address and subnet mask or prefix so the host can decide whether a destination is local. A wrong mask can cause it to ARP for a remote host or send a local host to its gateway incorrectly.", "The default gateway is the next hop for off-subnet traffic and must be reachable on the local subnet. DNS resolves names to records; it does not repair a missing route or unreachable gateway.", "DHCP can supply address, mask, gateway, and DNS configuration automatically. An APIPA IPv4 address in 169.254.0.0/16 often indicates a client did not obtain a DHCP lease, though a static configuration may be intentional."],
    { caption: "Host configuration supports local and remote decisions.", nodes: [{ title: "Address + mask", subtitle: "Determine local subnet" }, { title: "Local destination", subtitle: "Resolve neighbor on link" }, { title: "Remote destination", subtitle: "Send to gateway" }, { title: "DNS", subtitle: "Resolve names to records" }] },
    { title: "Diagnose missing access", scenario: "A workstation can reach local peers but cannot reach an off-subnet service by IP.", steps: ["Inspect its address, mask, and default gateway.", "Verify the gateway is in the workstation's local subnet and responds.", "Test a known remote IP separately from a DNS name."], check: "Which setting is most directly required to reach another IPv4 subnet?", choices: ["Default gateway", "Search suffix only", "MAC address table age", "SSID broadcast name"], answer: 0, explanation: "The host forwards off-subnet traffic to its default gateway. DNS is relevant only when resolving a name, not when testing by IP."}
  ),
  "wireless-basics": lesson(
    ["Relate frequency band, channel width, and interference to WLAN performance.", "Explain how attenuation and client density affect wireless service."],
    ["Wi-Fi uses shared radio spectrum. Clients and access points contend for airtime, so throughput depends not only on the advertised link rate but also on signal quality, channel use, protocol overhead, and other users.", "The 2.4 GHz band often reaches farther and penetrates obstacles better but has fewer non-overlapping channel choices and more interference sources. 5 GHz and 6 GHz can offer more channel capacity but may have shorter usable range and device/regulatory constraints.", "Channel planning, access-point placement, transmit-power balance, and capacity design matter. More access points do not automatically improve service if they create co-channel interference or poorly sized coverage cells."],
    { caption: "Radio quality and airtime jointly shape the client experience.", nodes: [{ title: "Client", subtitle: "Signal and capabilities" }, { title: "Shared channel", subtitle: "Contention and interference" }, { title: "Access point", subtitle: "Coverage and capacity" }, { title: "Wired LAN", subtitle: "Backhaul also matters" }] },
    { title: "Improve a congested WLAN", scenario: "Users report slow connections in a dense office despite strong signal.", steps: ["Check channel utilization and nearby co-channel/adjacent-channel interference.", "Review client count, channel width, and access-point placement.", "Make a measured channel or capacity change and compare performance."], check: "Why can strong signal coexist with poor throughput?", choices: ["High signal guarantees no contention", "A busy shared channel can limit airtime despite good signal", "DNS changes radio frequency", "Every client has a dedicated channel"], answer: 1, explanation: "Signal strength is only one factor. Clients share airtime, so interference or high channel utilization can reduce throughput even with a strong signal."}
  ),
  "virtualization": lesson(
    ["Describe virtual machines, hypervisors, and virtual switching.", "Trace how virtual networking maps to physical infrastructure."],
    ["A hypervisor allocates physical compute resources to virtual machines, each of which can have one or more virtual network interfaces. These interfaces behave like logical endpoints but depend on the host's underlying resources.", "A virtual switch forwards traffic among virtual ports and can connect a VM to a physical NIC. VLAN tagging and uplink configuration must align with the physical switch for traffic to reach the intended network.", "Virtualization improves flexibility and utilization, but it does not remove the need for addressing, routing, security policy, or capacity planning. A misconfigured virtual port group can isolate many VMs at once."],
    { caption: "A VM packet crosses logical and physical switching.", nodes: [{ title: "Virtual machine", subtitle: "Guest vNIC" }, { title: "Virtual switch", subtitle: "Port group and policy" }, { title: "Host uplink", subtitle: "Physical NIC" }, { title: "Physical switch", subtitle: "VLAN and routed path" }] },
    { title: "Trace a virtual host", scenario: "A VM cannot reach other systems in its assigned VLAN after a host migration.", steps: ["Confirm the VM's virtual NIC is connected to the intended port group.", "Check that the host uplink carries the required VLAN to the physical switch.", "Verify IP address, gateway, and reachability after each boundary."], check: "Which physical configuration is needed when the virtual uplink carries tagged VLANs?", choices: ["A matching allowed VLAN on the physical switch trunk", "A new DNS record only", "A TCP retransmission timer", "A different VM hostname"], answer: 0, explanation: "The physical uplink and switch port must carry the VM's VLAN; otherwise the virtual network cannot reach that Layer 2 segment."}
  ),
  "switching-concepts": lesson(
    ["Explain MAC learning and destination-based frame forwarding.", "Predict how a switch handles unknown unicast and broadcast frames."],
    ["A switch learns the source MAC address of an incoming frame and associates it with the ingress port and VLAN. Entries age out if they are not refreshed.", "For a known unicast destination, the switch forwards the frame only toward the learned port, unless that port is the ingress port. For an unknown unicast, it floods eligible ports in the same VLAN.", "Broadcast frames are also flooded within their VLAN, not across all VLANs by default. VLAN boundaries limit broadcast domains, while routing is needed to communicate between separate IP subnets."],
    { caption: "Learning creates a selective forwarding decision.", nodes: [{ title: "Frame arrives", subtitle: "Learn source MAC + VLAN" }, { title: "MAC table", subtitle: "Find destination port" }, { title: "Known unicast", subtitle: "Forward to one port" }, { title: "Unknown/broadcast", subtitle: "Flood within VLAN" }] },
    { title: "Predict a first-frame action", scenario: "A switch receives a unicast frame to a destination MAC it has not learned.", steps: ["Note the ingress VLAN and source MAC.", "Determine whether the destination MAC appears in that VLAN's table.", "Predict which ports receive the frame and where the switch learns."], check: "What does the switch normally do with an unknown unicast?", choices: ["Flood it to eligible ports in the same VLAN", "Route it to every VLAN", "Drop all frames until a router learns it", "Send it only to the default gateway"], answer: 0, explanation: "Unknown unicast is flooded within the VLAN except toward the ingress port; the switch learns the source MAC on that ingress port."}
  ),
  "vlans": lesson(
    ["Explain how VLANs create separate Layer 2 broadcast domains.", "Configure and verify access-port VLAN membership conceptually."],
    ["A VLAN is a logical Layer 2 segment. Switch ports assigned to different VLANs keep their broadcast traffic separate even when they share the same physical switch.", "An access port typically carries traffic for one untagged VLAN toward an endpoint. The endpoint's IP subnet should align with its VLAN, but VLAN membership itself does not assign an IP address.", "Hosts in different VLANs need a Layer 3 device to communicate. Verify VLAN existence and port assignment together; a correctly assigned access port in a nonexistent or inactive VLAN may not provide the intended service."],
    { caption: "VLAN membership separates user broadcast domains.", nodes: [{ title: "User A", subtitle: "Access port in VLAN 10" }, { title: "Switch", subtitle: "Separate MAC learning per VLAN" }, { title: "User B", subtitle: "Access port in VLAN 20" }, { title: "Router", subtitle: "Required for inter-VLAN traffic" }] },
    { title: "Place a host in its VLAN", scenario: "A new staff PC should join VLAN 20 on a lab switch.", steps: ["Confirm VLAN 20 exists and is active.", "Assign the endpoint-facing port to access mode and VLAN 20.", "Verify port membership and then test the expected subnet and gateway."], check: "Can two hosts in different VLANs communicate directly at Layer 2?", choices: ["Yes, VLAN tags are ignored everywhere", "No; inter-VLAN communication needs Layer 3 forwarding", "Yes, if they share a DNS server", "No; VLANs disable all switching"], answer: 1, explanation: "VLANs create separate Layer 2 broadcast domains. A router or Layer 3 switch must route between their IP subnets.", command: "show vlan brief"}
  ),
  "trunks": lesson(
    ["Distinguish access links from 802.1Q trunks.", "Explain allowed VLANs, native VLAN handling, and inter-VLAN routing."],
    ["An access link normally carries one VLAN without tagging to an endpoint. An 802.1Q trunk can carry multiple VLANs by adding VLAN tags to frames, allowing switches or a router-on-a-stick link to share one physical link.", "The native VLAN is carried untagged by default on many Cisco trunk configurations; both ends should agree on native VLAN and allowed VLANs. A mismatch can cause traffic leakage or operational warnings.", "A trunk transports VLANs but does not route between them. Inter-VLAN traffic needs a routed interface or subinterfaces with matching encapsulation and gateway addressing."],
    { caption: "Trunk transports multiple VLANs; routing connects them.", nodes: [{ title: "VLAN 10", subtitle: "Tagged on trunk" }, { title: "Trunk link", subtitle: "802.1Q allowed VLANs" }, { title: "VLAN 20", subtitle: "Tagged on trunk" }, { title: "Layer 3 gateway", subtitle: "Routes between subnets" }] },
    { title: "Restore VLAN reachability", scenario: "VLAN 20 works locally but is absent on a downstream switch.", steps: ["Check operational trunk state at both ends.", "Verify VLAN 20 is allowed and active along the path.", "Check native VLAN consistency and the Layer 3 gateway separately."], check: "Which setting is most likely to prevent VLAN 20 crossing the trunk?", choices: ["VLAN 20 is missing from the trunk allowed list", "The endpoint has a static DNS server", "The trunk is full duplex", "The router has a hostname"], answer: 0, explanation: "A VLAN excluded from the allowed list cannot traverse that trunk. A trunk alone also does not provide inter-VLAN routing.", command: "show interfaces trunk"}
  ),
  "discovery-protocols": lesson(
    ["Use CDP and LLDP to identify directly connected neighbors.", "Compare vendor-specific and open neighbor discovery behavior."],
    ["CDP is a Cisco discovery protocol that advertises information such as device identity, platform, and local/remote ports to directly connected Cisco-capable neighbors.", "LLDP is an IEEE vendor-neutral link-layer discovery protocol. It can help devices from different vendors describe their neighboring interfaces and capabilities.", "Neighbor discovery output is useful for inventory and troubleshooting, but it should be limited or disabled where disclosure is not acceptable. It identifies a direct link, not the full routed path to a remote device."],
    { caption: "Neighbor discovery describes one adjacent link.", nodes: [{ title: "Local interface", subtitle: "Sends discovery frames" }, { title: "CDP / LLDP", subtitle: "Link-local advertisements" }, { title: "Neighbor port", subtitle: "Remote interface identity" }] },
    { title: "Identify an unknown cable", scenario: "A switch port is patched into an undocumented device.", steps: ["Query the local device's neighbor table for the interface.", "Compare the advertised remote port and device identity with the plan.", "Use physical inspection if discovery is disabled or the neighbor is not participating."], check: "What is the primary scope of CDP/LLDP information?", choices: ["Directly connected neighbors", "Every router on the internet", "The complete DNS hierarchy", "All wireless clients regardless of AP"], answer: 0, explanation: "CDP and LLDP advertise link-local information about directly connected devices; they do not reveal a complete end-to-end route.", command: "show lldp neighbors"}
  ),
  "etherchannel": lesson(
    ["Explain why compatible physical links form one logical EtherChannel.", "Recognize LACP negotiation and common bundle consistency requirements."],
    ["EtherChannel groups compatible physical interfaces into a logical port-channel. Spanning Tree sees the bundle as one logical link, which can provide aggregate capacity across multiple flows and link redundancy.", "LACP is an open standard for negotiating link aggregation. Active mode initiates negotiation; passive mode responds, so at least one side must be active. Static mode does not negotiate and requires careful matching.", "Member links generally need consistent speed, duplex, trunk/access mode, allowed VLANs, and other relevant settings. A mismatch can keep links out of the bundle or cause inconsistent forwarding."],
    { caption: "Several compatible links act as one logical channel.", nodes: [{ title: "Physical link 1", subtitle: "Member of bundle" }, { title: "Physical link 2", subtitle: "Member of bundle" }, { title: "LACP", subtitle: "Negotiates membership" }, { title: "Port-channel", subtitle: "Logical link to STP" }] },
    { title: "Bring up an LACP channel", scenario: "Two switches have two parallel links intended as one trunk bundle.", steps: ["Match trunk/access settings and VLAN parameters on both members.", "Configure LACP so at least one endpoint actively initiates negotiation.", "Verify member state and the resulting logical port-channel."], check: "Which pairing can successfully negotiate LACP?", choices: ["Passive on both ends", "Active on one end and passive on the other", "No LACP on either end with different settings", "One link as routed and one as a trunk"], answer: 1, explanation: "An active LACP endpoint sends negotiation packets and a passive endpoint can respond. Passive/passive does not initiate negotiation.", command: "show etherchannel summary"}
  ),
  "spanning-tree": lesson(
    ["Explain how STP prevents Layer 2 forwarding loops.", "Identify root bridge selection and port roles at a high level."],
    ["Redundant Layer 2 links improve availability but can create loops in Ethernet, causing broadcast storms and MAC-table instability. Spanning Tree calculates a loop-free active topology while leaving alternate paths available.", "Switches exchange BPDUs and elect a root bridge using bridge ID, including priority and MAC address. Ports are selected as root, designated, or alternate roles according to path cost and tie-breakers.", "Rapid PVST+ runs a rapid spanning-tree instance per VLAN on Cisco switches. A blocked or alternate port is not necessarily a fault; it can be the protection that keeps the VLAN loop-free until a path failure."],
    { caption: "STP keeps redundancy while blocking a loop-forming path.", nodes: [{ title: "Switch A", subtitle: "Root bridge" }, { title: "Forwarding path", subtitle: "Root/designated ports" }, { title: "Redundant link", subtitle: "Alternate, non-forwarding" }, { title: "Failure", subtitle: "Alternate can take over" }] },
    { title: "Understand a blocked redundant port", scenario: "A redundant campus link is not forwarding under normal conditions.", steps: ["Inspect the STP root and port role/state for the affected VLAN.", "Confirm a separate forwarding path exists and no unexpected root is present.", "Test failover only in a controlled maintenance window."], check: "Why might STP intentionally place a redundant port in an alternate state?", choices: ["To prevent a Layer 2 loop while retaining a backup path", "To assign a default gateway", "To encrypt frames", "To force an OSPF neighbor"], answer: 0, explanation: "STP blocks a loop-forming redundant path during normal operation but can transition it if the active topology fails.", command: "show spanning-tree"}
  ),
  "edge-protection": lesson(
    ["Use PortFast only on appropriate endpoint-facing access ports.", "Explain how BPDU Guard responds to unexpected spanning-tree BPDUs."],
    ["PortFast allows an edge port connected to an endpoint to move quickly to forwarding instead of waiting through traditional STP transitions. It should not be used casually on switch-to-switch links.", "BPDU Guard protects edge ports by placing a port into an error-disabled state if a BPDU arrives. This can reveal an unauthorized switch or an incorrectly cabled bridge.", "A recovery procedure should identify the cause before re-enabling the port. PortFast does not disable spanning tree, and BPDU Guard is a safety mechanism rather than a substitute for a sound topology."],
    { caption: "Edge features accelerate endpoints and guard against bridges.", nodes: [{ title: "Endpoint port", subtitle: "PortFast edge behavior" }, { title: "Unexpected BPDU", subtitle: "Detected on edge" }, { title: "BPDU Guard", subtitle: "Disables protected port" }] },
    { title: "Protect a user-facing port", scenario: "A desk port should come up quickly but must not accept an unapproved switch.", steps: ["Confirm the port is a true endpoint-facing access port.", "Enable edge/PortFast behavior and BPDU Guard according to policy.", "If the port disables, locate the sending bridge before recovery."], check: "What happens when BPDU Guard receives a BPDU on a protected edge port?", choices: ["The port is placed into an error-disabled state", "The switch becomes a DHCP server", "The VLAN is automatically routed", "The BPDU is converted to an IP packet"], answer: 0, explanation: "BPDU Guard shuts down the protected edge port on receipt of a BPDU, helping prevent an unexpected Layer 2 bridge from creating a loop.", command: "show spanning-tree interface"}
  ),
  "wireless-architecture": lesson(
    ["Compare autonomous and centrally managed wireless architectures.", "Describe common AP operational roles and controller coordination."],
    ["An autonomous AP can be configured and managed individually, which may suit a small deployment but can make consistent policy harder at scale. A controller-based WLAN centralizes configuration and operational visibility.", "In a controller-based design, APs establish a control relationship with the wireless LAN controller. Depending on architecture and forwarding mode, client data may be tunneled to the controller or locally bridged.", "AP modes serve different purposes: local mode provides client access, while monitor or specialized modes may focus on monitoring, rogue detection, or other functions. A controller is not necessarily the client data path for every WLAN."],
    { caption: "Management and client data may follow distinct paths.", nodes: [{ title: "AP radio", subtitle: "Serves client association" }, { title: "Control tunnel", subtitle: "AP management to WLC" }, { title: "Client traffic", subtitle: "Central or local switching" }, { title: "Wired network", subtitle: "Carries mapped VLANs" }] },
    { title: "Trace managed AP behavior", scenario: "A centrally managed AP is online but its WLAN configuration has not appeared.", steps: ["Check AP reachability and discovery/join to its intended controller.", "Verify controller policy and AP group/WLAN assignment.", "Determine whether client traffic is centrally tunneled or locally switched."], check: "Does controller-based management always mean all user data traverses the controller?", choices: ["Yes, every WLAN must tunnel all data", "No, forwarding mode can centralize or locally switch client traffic", "Yes, because APs have no Ethernet ports", "No, because WLANs do not use controllers"], answer: 1, explanation: "Control-plane management and client data forwarding are separate design choices; local switching is possible in controller-managed deployments."}
  ),
  "wireless-connections": lesson(
    ["Trace AP power, wired uplink, VLAN, and IP connectivity requirements.", "Differentiate an RF association problem from an upstream wired-path problem."],
    ["An access point needs physical network connectivity and often power over Ethernet from a capable switch or injector. The link speed and power budget should match the AP requirements.", "The switch port may carry management traffic and one or more client VLANs, either as an access connection or trunk depending on deployment. A client can associate successfully while its DHCP or routed service still fails upstream.", "Troubleshoot one layer at a time: AP link and power, controller or management reachability, WLAN-to-VLAN mapping, then client address and gateway. This avoids mistaking a wired VLAN fault for an RF fault."],
    { caption: "Wireless service relies on the wired path behind the AP.", nodes: [{ title: "Client radio", subtitle: "Association to SSID" }, { title: "AP", subtitle: "RF bridge and PoE device" }, { title: "Switch uplink", subtitle: "Management/client VLANs" }, { title: "Gateway + DHCP", subtitle: "Client network services" }] },
    { title: "Troubleshoot no client address", scenario: "Clients associate to an SSID but receive no usable IP configuration.", steps: ["Confirm AP uplink and power are stable.", "Verify WLAN-to-VLAN mapping and that the VLAN is carried to its gateway.", "Check the DHCP service or relay path for that client subnet."], check: "Which diagnosis best fits association succeeding but DHCP failing?", choices: ["Investigate the wired client VLAN and DHCP path", "Assume the RF association is impossible", "Change the client's TCP window", "Disable the router's routing table"], answer: 0, explanation: "Successful association indicates the radio connection exists. Missing IP configuration points next to VLAN transport, gateway, DHCP server, or relay."}
  ),
  "wlan-security": lesson(
    ["Relate SSID, security policy, and VLAN mapping.", "Choose modern WLAN authentication and encryption appropriate to a deployment."],
    ["An SSID is the WLAN name advertised to clients, but its name alone does not provide security. Each WLAN should map clients to the intended network and apply a deliberate authentication policy.", "Personal mode commonly uses a pre-shared key; enterprise mode uses 802.1X/EAP with an authentication server and per-user or per-device credentials. WPA2-AES and WPA3 are preferable to obsolete WEP or TKIP configurations.", "A secure design also considers guest isolation, management protections, key rotation, and client compatibility. A correctly encrypted WLAN can still be misconfigured if it places guests into a trusted corporate VLAN."],
    { caption: "A secure WLAN combines identity, protection, and segmentation.", nodes: [{ title: "SSID", subtitle: "Advertised service name" }, { title: "Authentication", subtitle: "PSK or 802.1X/EAP" }, { title: "Encryption", subtitle: "Protect radio data" }, { title: "VLAN/policy", subtitle: "Constrain client reach" }] },
    { title: "Design a staff WLAN", scenario: "An office needs individual staff authentication and separation from guests.", steps: ["Choose enterprise authentication with a trusted identity service.", "Map the staff WLAN to the approved staff VLAN and policy.", "Test authentication, encryption, and guest isolation with test clients."], check: "Which option best supports individual staff identities at scale?", choices: ["Open WLAN with a hidden SSID", "One shared WEP key", "WPA2/WPA3-Enterprise with 802.1X/EAP", "MAC address naming only"], answer: 2, explanation: "Enterprise WLAN security uses 802.1X/EAP authentication and modern encryption, supporting identity-based access rather than a shared legacy key."}
  ),
  "routing-table": lesson(
    ["Read route source, prefix, next hop, and outgoing interface.", "Distinguish a routing table from the forwarding decision for a particular packet."],
    ["A routing table records reachable destination prefixes and route attributes. Entries can be learned as connected, static, or from dynamic routing protocols, each with its own code and administrative preference.", "A route may name a next-hop address, an exit interface, or both. Connected routes represent directly attached networks; a host route (/32 for IPv4 or /128 for IPv6) identifies one destination.", "To predict forwarding, compare the destination to matching prefixes and use the most specific route. The route table does not contain every possible destination; when there is no matching route, the packet may be dropped unless a default route exists."],
    { caption: "Route entry guides the next forwarding step.", nodes: [{ title: "Destination IP", subtitle: "Packet being forwarded" }, { title: "Prefix lookup", subtitle: "Match route entries" }, { title: "Next hop", subtitle: "Neighbor router if needed" }, { title: "Exit interface", subtitle: "Send packet onward" }] },
    { title: "Read a route", scenario: "A route shows 198.51.100.0/24 via 10.0.0.2 out GigabitEthernet0/0.", steps: ["Compare the packet destination with the /24 network.", "Identify the next-hop address and local outgoing interface.", "Confirm the next hop is itself reachable through the routing table."], check: "What does 10.0.0.2 represent in this route?", choices: ["The destination host in the /24", "The next-hop router", "The IPv4 broadcast address", "The route's subnet mask"], answer: 1, explanation: "The route points packets matching 198.51.100.0/24 toward next-hop 10.0.0.2 via the specified local interface.", command: "show ip route"}
  ),
  "route-selection": lesson(
    ["Apply longest-prefix match when multiple routes match a destination.", "Distinguish prefix specificity from administrative distance and metric."],
    ["Routers first select the matching route with the longest prefix, meaning the greatest number of matching network bits. A /24 is more specific than a /16 and wins for a destination inside both.", "Administrative distance compares the trustworthiness of different route sources for the same prefix on Cisco devices; a lower value is preferred. A protocol's metric then helps compare candidate routes within that protocol.", "These decisions are distinct: a less trusted source can still provide the selected route if it is the only source for a more-specific prefix. Do not compare administrative distance before longest-prefix matching."],
    { caption: "Specificity chooses the destination match before route-source preference.", nodes: [{ title: "Destination", subtitle: "198.51.100.25" }, { title: "/16 route", subtitle: "Broad match" }, { title: "/24 route", subtitle: "More-specific match wins" }, { title: "Next hop", subtitle: "Forward using /24" }] },
    { title: "Select the matching route", scenario: "A router has 198.51.0.0/16 and 198.51.100.0/24 installed.", steps: ["Check which prefixes contain 198.51.100.25.", "Compare their prefix lengths.", "Choose the next hop associated with the longest matching prefix."], check: "Which route is used for 198.51.100.25?", choices: ["198.51.0.0/16", "198.51.100.0/24", "Both equally", "Neither, because they overlap"], answer: 1, explanation: "Both prefixes match, but /24 is more specific than /16, so longest-prefix match selects the /24."}
  ),
  "static-routes": lesson(
    ["Configure the purpose of IPv4 and IPv6 static routes conceptually.", "Explain default routes and the importance of a reachable next hop."],
    ["A static route is manually configured for a destination prefix and specifies a next hop, outgoing interface, or both. It is useful for small stable paths, stub networks, and controlled route injection.", "A default route, 0.0.0.0/0 in IPv4 or ::/0 in IPv6, matches any destination that has no more-specific route. It is commonly pointed toward an upstream provider or edge router.", "The next hop must be resolvable and reachable, or forwarding cannot complete. A static route does not automatically provide a return path; bidirectional communication requires routes in both directions."],
    { caption: "A default route forwards unmatched destinations upstream.", nodes: [{ title: "LAN", subtitle: "Known connected prefix" }, { title: "Route lookup", subtitle: "No specific destination match" }, { title: "Default route", subtitle: "0.0.0.0/0 or ::/0" }, { title: "Upstream", subtitle: "Next-hop router" }] },
    { title: "Add a lab default path", scenario: "A stub router has a working LAN and a directly connected WAN next hop.", steps: ["Confirm the upstream next-hop address is on a connected network.", "Install an IPv4 or IPv6 default route pointing toward it.", "Verify the route and test both outbound and return reachability."], check: "What does a default route match?", choices: ["Only the local subnet", "Destinations without a more-specific matching route", "Only broadcast traffic", "Only directly connected neighbors"], answer: 1, explanation: "A default route is the least-specific route and is used only when no more-specific matching route is available.", command: "show ip route"}
  ),
  "ospf": lesson(
    ["Describe OSPF neighbor formation and link-state route calculation.", "Recognize common single-area OSPFv2 adjacency prerequisites."],
    ["OSPF is a link-state interior gateway protocol. Routers discover neighbors with Hello packets, exchange link-state information, and run the shortest-path-first algorithm to calculate paths.", "On a shared link, OSPF neighbors generally need compatible area IDs, subnet settings, timers, and authentication policy; router IDs must be unique. A mismatch can prevent adjacency even when IP connectivity works.", "An OSPF-enabled interface can advertise a connected prefix and form neighbors according to configuration. In a single-area design, all participating links belong to area 0; verify neighbor state and learned routes rather than assuming a configured process is operational."],
    { caption: "OSPF shares topology and computes best paths.", nodes: [{ title: "Hello exchange", subtitle: "Discover compatible peers" }, { title: "Adjacency", subtitle: "Synchronize link-state data" }, { title: "Link-state database", subtitle: "Topology view" }, { title: "SPF calculation", subtitle: "Install best routes" }] },
    { title: "Troubleshoot missing OSPF route", scenario: "Two directly connected routers cannot see each other's OSPF routes.", steps: ["Check interface addressing and IP reachability.", "Compare area, timers, network type, authentication, and router IDs.", "Inspect neighbor state, then verify the prefix is advertised and installed."], check: "Which mismatch commonly prevents OSPF neighbors from forming?", choices: ["Different OSPF area IDs on the shared link", "Different device hostnames", "Different DNS search suffixes", "Different console line speeds"], answer: 0, explanation: "OSPF peers on a shared link must agree on the area and other required parameters; different area IDs prevent normal adjacency.", command: "show ip ospf neighbor"}
  ),
  "first-hop-redundancy": lesson(
    ["Explain the purpose of a virtual default gateway.", "Describe active/standby behavior in a first-hop redundancy protocol."],
    ["A host ordinarily has one configured default gateway. If that router fails, the host may lose off-subnet access even when another router is available.", "First-hop redundancy protocols such as HSRP provide a virtual IP and virtual MAC shared by a group of routers. One router forwards as active while another is ready to take over.", "Hosts continue using the virtual gateway rather than changing their configuration during failover. Redundancy depends on healthy Layer 2 connectivity, correct group settings, and appropriate tracking or priority behavior."],
    { caption: "Routers share a virtual gateway identity for hosts.", nodes: [{ title: "Host", subtitle: "Uses virtual gateway IP" }, { title: "Active router", subtitle: "Forwards current traffic" }, { title: "Standby router", subtitle: "Ready for takeover" }, { title: "Failover", subtitle: "Virtual service continues" }] },
    { title: "Plan gateway resilience", scenario: "Users must retain the same gateway address if one distribution router fails.", steps: ["Configure both routers in a matching redundancy group on the client VLAN.", "Set the shared virtual IP and deliberate priority/preemption policy.", "Test controlled failover while checking host gateway and routed reachability."], check: "What address should clients normally use as their default gateway?", choices: ["The active router's changing physical address", "The shared virtual gateway address", "The standby router's loopback only", "A public DNS resolver"], answer: 1, explanation: "Clients use the stable virtual IP. The active physical router can change while the host configuration remains unchanged."}
  ),
  "nat": lesson(
    ["Differentiate static, dynamic, and overload/PAT translation concepts.", "Trace how translation changes packet addresses at a network edge."],
    ["NAT changes address information as packets cross a boundary. Static NAT commonly maps one inside address to one stable outside address; dynamic NAT allocates from a pool.", "Port Address Translation (PAT), often called NAT overload, allows multiple inside hosts to share an outside IPv4 address by tracking transport identifiers such as TCP/UDP ports. Translation state permits return traffic to be mapped to the correct inside flow.", "NAT is not a replacement for routing, firewall policy, or encryption. Verify inside/outside interface roles, address pools, ACL match conditions, and return routes when a translation does not work."],
    { caption: "PAT tracks multiple inside flows through one outside address.", nodes: [{ title: "Inside host", subtitle: "Private source + port" }, { title: "NAT/PAT edge", subtitle: "Creates translation state" }, { title: "Outside address", subtitle: "Shared translated source" }, { title: "Reply", subtitle: "State maps flow back inside" }] },
    { title: "Share an outside address", scenario: "Several private lab clients need outbound reachability through one public-facing interface.", steps: ["Identify inside and outside interfaces and the private source subnet.", "Configure overload/PAT using the approved outside address or interface.", "Verify translation entries and test a return flow."], check: "How can PAT distinguish simultaneous flows using one outside IPv4 address?", choices: ["By tracking transport ports and protocol state", "By changing the DNS name", "By using VLAN IDs as public IPs", "It cannot distinguish flows"], answer: 0, explanation: "PAT tracks transport-layer identifiers, allowing multiple inside flows to share an address while replies map to the correct translation.", command: "show ip nat translations"}
  ),
  "ntp": lesson(
    ["Explain why consistent time is important for network operations.", "Identify client/server roles and safe NTP verification steps."],
    ["NTP synchronizes clocks among devices using a hierarchy of time sources. Accurate time helps correlate syslog events, authentication records, packet captures, and incident timelines.", "A device configured as an NTP client synchronizes from a reachable server; it does not automatically become an authoritative source for all peers. Stratum indicates distance from a reference clock, not a simple quality score by itself.", "Time synchronization depends on reachability, correct source configuration, and appropriate firewall policy. Use a trusted organizational source and verify synchronization state rather than relying only on a configured server line."],
    { caption: "A trusted time source keeps operational records aligned.", nodes: [{ title: "Reference clock", subtitle: "Trusted upstream source" }, { title: "NTP server", subtitle: "Distributes synchronized time" }, { title: "Router / switch", subtitle: "NTP client" }, { title: "Logs", subtitle: "Comparable timestamps" }] },
    { title: "Synchronize a device clock", scenario: "Switch logs differ by several minutes from the central monitoring system.", steps: ["Check the device's current clock, timezone, and synchronization status.", "Configure the approved reachable NTP server and required access.", "Recheck synchronization and compare a new event timestamp."], check: "Why is NTP useful during multi-device troubleshooting?", choices: ["It encrypts all syslog messages", "It aligns timestamps so events can be correlated", "It assigns VLAN membership", "It replaces routing protocols"], answer: 1, explanation: "Consistent time allows operators to correlate events across network devices and monitoring systems.", command: "show ntp status"}
  ),
  "dhcp-dns": lesson(
    ["Distinguish DHCP address configuration from DNS name resolution.", "Explain the DHCP lease exchange and common relay requirement."],
    ["DHCP dynamically provides clients with an address lease and options such as subnet mask, default gateway, and DNS server. The basic IPv4 exchange is Discover, Offer, Request, Acknowledge (DORA).", "DHCP broadcasts are local to a subnet, so a router does not normally forward them by default. A DHCP relay agent can forward client requests to a server on another subnet.", "DNS maps names to records such as A and AAAA addresses. A client can have working IP connectivity but fail by hostname if DNS is misconfigured; conversely, successful DNS resolution does not prove the destination is reachable."],
    { caption: "DHCP configures a client before DNS resolves names.", nodes: [{ title: "DHCP Discover", subtitle: "Client broadcasts request" }, { title: "Relay/server", subtitle: "Offer and lease" }, { title: "Client config", subtitle: "Address, gateway, DNS" }, { title: "DNS query", subtitle: "Name resolves to record" }] },
    { title: "Repair a remote DHCP scope", scenario: "A client VLAN has no local DHCP server, but a central DHCP server is available.", steps: ["Verify VLAN gateway and client broadcast reach the router interface.", "Configure a relay/helper toward the authorized DHCP server.", "Renew a test lease and inspect the offered subnet, gateway, and DNS values."], check: "What service resolves a domain name after a client has its IP configuration?", choices: ["DHCP", "DNS", "STP", "NTP"], answer: 1, explanation: "DNS resolves names to resource records. DHCP supplies host configuration including which DNS resolver to use."}
  ),
  "monitoring": lesson(
    ["Compare SNMP monitoring with syslog event reporting.", "Explain secure, useful telemetry collection and time correlation."],
    ["SNMP can expose counters, state, and management objects for polling or send notifications such as traps. SNMPv3 supports authentication and privacy features and is preferable to plaintext community strings where supported.", "Syslog sends event messages to a collector, helping centralize faults and state changes. Severity levels classify message urgency; syslog is event-oriented and does not replace periodic interface-counter polling.", "Monitoring is only useful when devices can reach collectors and timestamps are aligned. Restrict management-plane access, protect credentials, and tune alert thresholds so important events are not hidden by noise."],
    { caption: "Polling metrics and event messages complement one another.", nodes: [{ title: "Device counters", subtitle: "SNMP polling/notifications" }, { title: "Device events", subtitle: "Syslog messages" }, { title: "Collector", subtitle: "Central storage and correlation" }, { title: "Operator", subtitle: "Alert and investigate" }] },
    { title: "Investigate a link flap", scenario: "Monitoring reports intermittent loss on a switch uplink.", steps: ["Review timestamped syslog for interface state changes.", "Compare SNMP interface counters and error deltas around the event.", "Correlate both sources with maintenance and peer-device records."], check: "Which source is best suited to periodic interface counter polling?", choices: ["SNMP", "DNS", "DHCP", "802.1Q"], answer: 0, explanation: "SNMP can poll management information such as interface counters. Syslog complements it by reporting event messages.", command: "show logging"}
  ),
  "qos": lesson(
    ["Explain classification, marking, queuing, and congestion management.", "Recognize QoS as prioritization rather than added bandwidth."],
    ["QoS identifies traffic classes, marks packets (often with DSCP), and applies policies such as queuing or policing. Classification may use access control lists, ports, or trusted markings, depending on design.", "Queues matter most when a link is congested. Priority treatment can reduce delay and jitter for latency-sensitive traffic, while shaping smooths transmission and policing can rate-limit or drop excess traffic.", "QoS does not create capacity and cannot fix a persistently oversubscribed path by itself. End-to-end trust boundaries and consistent treatment are needed; indiscriminate priority marking can harm other traffic."],
    { caption: "QoS treatment operates at classification and congestion points.", nodes: [{ title: "Ingress traffic", subtitle: "Classify flows" }, { title: "Marking", subtitle: "Apply/validate DSCP" }, { title: "Queues", subtitle: "Schedule under congestion" }, { title: "Egress link", subtitle: "Transmit by policy" }] },
    { title: "Protect voice under congestion", scenario: "Voice becomes choppy while a large file transfer saturates an uplink.", steps: ["Identify and validate voice traffic classification and markings.", "Apply an appropriate queuing policy at the congested egress point.", "Measure voice delay/loss and bulk throughput after the change."], check: "What does QoS do when a link is congested?", choices: ["Creates new physical bandwidth", "Prioritizes and manages traffic treatment", "Guarantees every packet has zero delay", "Replaces the routing table"], answer: 1, explanation: "QoS manages which traffic is served and how under congestion; it does not add link capacity or guarantee perfect delivery."}
  ),
  "ssh": lesson(
    ["Explain SSH encryption and its role in device management.", "Identify the minimum safe elements of a managed CLI access path."],
    ["SSH provides an encrypted remote terminal session, protecting credentials and commands in transit compared with plaintext protocols such as Telnet. Server identity verification helps prevent connecting to an impersonated device.", "Secure device access also needs local or centralized authentication, authorization, management-plane filtering, and protected key handling. Encryption alone does not decide whether an administrator should be allowed to run a command.", "Use a designated management network and restrict remote access to approved sources. Test a non-disruptive login before closing a maintenance session, and maintain an approved recovery path."],
    { caption: "A managed SSH session has identity, policy, and encrypted transport.", nodes: [{ title: "Admin host", subtitle: "Approved management source" }, { title: "SSH handshake", subtitle: "Verify identity and negotiate" }, { title: "Device", subtitle: "Authenticate and authorize" }, { title: "Encrypted CLI", subtitle: "Protected session" }] },
    { title: "Harden remote CLI access", scenario: "A lab router still accepts unencrypted Telnet from user VLANs.", steps: ["Enable and test SSH with approved authentication and host keys.", "Restrict management access to the administrator subnet.", "Disable Telnet after verifying SSH access and the recovery method."], check: "Why is SSH preferable to Telnet for remote administration?", choices: ["SSH encrypts the session; Telnet sends it in plaintext", "SSH automatically prevents every configuration error", "Telnet uses stronger encryption", "SSH replaces authorization policy"], answer: 0, explanation: "SSH encrypts remote management traffic. It should still be combined with authentication, authorization, and source restrictions.", command: "show ip ssh"}
  ),
  "file-transfer": lesson(
    ["Select a suitable protocol and workflow for device file transfer.", "Protect configuration and image transfers with validation and access controls."],
    ["Network devices transfer configuration backups, software images, and diagnostic files using services such as SCP, SFTP, or TFTP. TFTP is simple but provides no authentication or encryption, so it belongs only in appropriately controlled environments.", "Before moving an image, check platform compatibility, storage, integrity hash, and approved change procedure. A successful copy is not proof that an image is valid or bootable.", "Configuration backups can contain sensitive information. Restrict repository access, encrypt data in transit and at rest where possible, and test restore procedures in a safe environment."],
    { caption: "A safe transfer includes authorization and integrity checks.", nodes: [{ title: "Device", subtitle: "Prepare and stage file" }, { title: "Transfer service", subtitle: "SCP/SFTP or controlled TFTP" }, { title: "Repository", subtitle: "Restricted storage" }, { title: "Validation", subtitle: "Hash and restore test" }] },
    { title: "Back up a lab configuration", scenario: "A planned maintenance requires a recoverable configuration copy.", steps: ["Select an approved reachable repository and secure transfer method.", "Copy the configuration without exposing it in an untrusted location.", "Verify file presence, permissions, and recoverability before maintenance."], check: "Which statement about TFTP is correct?", choices: ["It encrypts and authenticates every transfer by default", "It is simple but lacks built-in authentication and encryption", "It is a routing protocol", "It replaces image integrity verification"], answer: 1, explanation: "TFTP is a lightweight file transfer protocol without built-in security controls; use a protected environment or a secure alternative.", command: "copy running-config scp:"}
  ),
  "threats": lesson(
    ["Distinguish threats, vulnerabilities, and risk.", "Match layered mitigations to common network attack paths."],
    ["A threat is a potential cause of harm; a vulnerability is a weakness that could be exploited; risk considers likelihood and impact. A threat actor may exploit a vulnerable service, but exposure and controls affect the actual risk.", "Mitigations reduce opportunities or impact: patching closes known weaknesses, segmentation limits lateral movement, strong authentication reduces account compromise, and monitoring improves detection.", "Security is layered and ongoing. Prioritize exposed assets and business impact, validate control effectiveness, and maintain response procedures rather than relying on one perimeter device."],
    { caption: "Risk treatment addresses weaknesses and potential impact.", nodes: [{ title: "Threat", subtitle: "Potential harmful event" }, { title: "Vulnerability", subtitle: "Weakness in asset/control" }, { title: "Mitigation", subtitle: "Reduce likelihood or impact" }, { title: "Monitoring", subtitle: "Detect and respond" }] },
    { title: "Reduce exposed management risk", scenario: "A router management service is reachable from an untrusted user network.", steps: ["Inventory the service and identify who needs administrative access.", "Restrict access to a dedicated management path and approved sources.", "Patch, monitor access attempts, and verify the restriction."], check: "Which change most directly reduces the attack surface?", choices: ["Allow access from every subnet", "Restrict management to authorized sources and disable unused services", "Share one administrator password", "Turn off event logging"], answer: 1, explanation: "Limiting management reachability and removing unused services reduce exposure while preserving intended administration."}
  ),
  "security-programs": lesson(
    ["Explain how security policies translate into operational controls.", "Relate least privilege, acceptable use, and incident reporting to network practice."],
    ["A security program defines governance, responsibilities, risk processes, and review cycles. Policies express expected behavior; standards and procedures make those expectations actionable.", "Least privilege grants each user or service only the access required for its role. Acceptable-use and change-management policies help reduce accidental exposure and make network changes traceable.", "Training, reporting channels, audits, and incident response are essential complements to technical controls. Policies should be clear, approved, communicated, and updated as technology and risks change."],
    { caption: "Governance becomes practical controls and reviewed behavior.", nodes: [{ title: "Policy", subtitle: "Intent and requirements" }, { title: "Procedure", subtitle: "Repeatable steps" }, { title: "Technical control", subtitle: "Enforced network behavior" }, { title: "Review", subtitle: "Evidence and improvement" }] },
    { title: "Apply least privilege", scenario: "A help-desk role needs to inspect interface status but should not alter routing.", steps: ["Define the tasks and minimum command permissions required.", "Use role-based authorization rather than a shared full-privilege account.", "Review access logs and remove permissions no longer needed."], check: "What does least privilege mean?", choices: ["Every user receives administrator access", "Grant only the permissions necessary for the user's role", "Disable all user accounts", "Use one password for all devices"], answer: 1, explanation: "Least privilege limits access to what a user needs for assigned work, reducing the impact of mistakes or compromised accounts."}
  ),
  "device-access": lesson(
    ["Harden network-device management access.", "Combine authentication, authorization, transport security, and management-plane limits."],
    ["A device's management plane should be reachable only from trusted administration paths. Restricting source subnets and disabling unused services reduces exposure.", "Use individual accounts or centralized identity where appropriate, strong authentication, and role-based authorization. Authentication proves identity; authorization limits what that identity can do.", "Protect secrets, use encrypted management protocols, maintain logs, and test a recovery process. A secure configuration should not lock out legitimate administrators during a failed authentication service."],
    { caption: "Device access controls protect each management stage.", nodes: [{ title: "Trusted admin network", subtitle: "Source restriction" }, { title: "SSH / HTTPS", subtitle: "Encrypted transport" }, { title: "AAA", subtitle: "Identity and permissions" }, { title: "Audit logs", subtitle: "Accountability" }] },
    { title: "Restrict management access", scenario: "A switch's management interface currently accepts SSH from all user subnets.", steps: ["Define the approved administrator source range.", "Apply a management ACL and verify that it permits required access only.", "Test access from both an approved host and a denied user subnet."], check: "Which control limits where administrators can connect from?", choices: ["Management-plane access ACL", "STP root priority", "DHCP lease duration", "QoS queue weight"], answer: 0, explanation: "A management access ACL restricts source addresses allowed to connect to device management services; authentication and authorization still apply.", command: "show access-lists"}
  ),
  "acls": lesson(
    ["Interpret ordered ACL evaluation and implicit deny behavior.", "Place and test an ACL to permit intended traffic while limiting other traffic."],
    ["An ACL processes entries in order and uses the first matching rule. More-specific permits or denies should appear before broader rules that would otherwise match first.", "There is an implicit deny at the end of a Cisco ACL. If intended traffic should be allowed, it must match an explicit permit; an ACL with no match can silently block packets.", "Standard IPv4 ACLs primarily match source addresses, while extended ACLs can match protocol, source, destination, and ports. Direction and interface placement affect which traffic is evaluated."],
    { caption: "Ordered rules decide whether a packet passes.", nodes: [{ title: "Packet arrives", subtitle: "Evaluate interface/direction" }, { title: "Rule 1...N", subtitle: "First matching entry wins" }, { title: "Explicit permit", subtitle: "Forward if allowed" }, { title: "No match", subtitle: "Implicit deny" }] },
    { title: "Permit one service", scenario: "A simulated extended ACL should permit an approved subnet to a web server and deny other sources.", steps: ["Place a specific permit for the approved source and destination service first.", "Add any required explicit deny or later permits in deliberate order.", "Apply the ACL in the intended direction and test permitted and denied cases."], check: "What happens when no ACL entry matches a packet?", choices: ["It is implicitly denied", "It is implicitly permitted", "It is sent to DNS", "It is broadcast to all VLANs"], answer: 0, explanation: "Cisco ACLs have an implicit deny at the end. Add explicit permits for legitimate traffic and verify placement and direction."}
  ),
  "layer2-security": lesson(
    ["Describe port security and other Layer 2 edge protections.", "Recognize why DHCP snooping, DAI, and BPDU protection address different threats."],
    ["Layer 2 security controls guard the local switching domain. Port security can limit or control learned MAC addresses on access ports, while BPDU Guard protects edge ports from unexpected bridges.", "DHCP snooping builds a binding table and can block untrusted DHCP server replies; Dynamic ARP Inspection can validate ARP messages against trusted bindings. Their trust settings must match the topology.", "These controls are complementary and must be deployed carefully to avoid blocking legitimate services. Define trusted uplinks, test endpoint behavior, and monitor violations before broad rollout."],
    { caption: "Different edge controls protect distinct Layer 2 behaviors.", nodes: [{ title: "Access port", subtitle: "Port security / BPDU Guard" }, { title: "DHCP snooping", subtitle: "Trusted server path" }, { title: "Binding table", subtitle: "Address validation data" }, { title: "DAI", subtitle: "Inspect ARP claims" }] },
    { title: "Contain a rogue DHCP server", scenario: "A user-facing port should not be able to serve DHCP leases to the VLAN.", steps: ["Identify the legitimate DHCP server-facing or relay path.", "Keep user-facing ports untrusted and configure the legitimate path appropriately.", "Test a client lease and inspect snooping counters without disrupting service."], check: "Which feature helps block DHCP server messages arriving on an untrusted edge port?", choices: ["DHCP snooping", "NTP", "PortFast alone", "NAT overload"], answer: 0, explanation: "DHCP snooping distinguishes trusted server paths from untrusted ports and can drop unauthorized DHCP server replies."}
  ),
  "aaa": lesson(
    ["Distinguish authentication, authorization, and accounting.", "Explain how centralized AAA supports consistent device administration."],
    ["Authentication verifies identity, for example with credentials or a multifactor challenge. It answers who is connecting.", "Authorization determines what an authenticated identity may do, such as which commands or privilege level is permitted. Accounting records relevant actions and session details for audit and troubleshooting.", "RADIUS and TACACS+ are common AAA protocols, with different designs and capabilities. Centralized AAA improves consistency but should have a tested local fallback and protected communication to avoid administrative lockout."],
    { caption: "AAA separates identity, permission, and audit.", nodes: [{ title: "Login", subtitle: "Authentication: who?" }, { title: "Command request", subtitle: "Authorization: allowed?" }, { title: "Session activity", subtitle: "Accounting: what happened?" }, { title: "AAA server", subtitle: "Central policy and records" }] },
    { title: "Assign command-level access", scenario: "A junior operator may inspect configuration but must not change it.", steps: ["Authenticate the operator through the approved identity source.", "Assign a read-only role with only required show commands.", "Enable accounting and verify attempted privileged changes are denied and logged."], check: "Which AAA function decides whether a user may run a configuration command?", choices: ["Authentication", "Authorization", "Accounting", "Address resolution"], answer: 1, explanation: "Authorization maps an authenticated identity to allowed commands and privileges. Accounting records actions but does not grant them."}
  ),
  "vpn": lesson(
    ["Explain how VPN tunneling protects traffic across an untrusted network.", "Distinguish remote-access and site-to-site VPN use cases."],
    ["A VPN creates a logical tunnel across an underlying network. IPsec commonly protects site-to-site or remote-access IP traffic with confidentiality, integrity, and peer authentication when configured correctly.", "Remote-access VPN connects an individual user's device to organizational resources; site-to-site VPN connects networks through security gateways. Tunneling and encryption do not remove the need for routing and access policy.", "Troubleshoot both tunnel control and user data: peer reachability, compatible security parameters, authentication, routes, selectors, and firewall policy. A tunnel can be up while the desired application remains unreachable."],
    { caption: "Protected packets cross an untrusted transport.", nodes: [{ title: "Branch LAN", subtitle: "Original traffic" }, { title: "VPN gateway", subtitle: "Authenticate and encapsulate" }, { title: "Untrusted network", subtitle: "Carries protected tunnel" }, { title: "Remote gateway", subtitle: "Decapsulate to destination LAN" }] },
    { title: "Troubleshoot a site VPN", scenario: "A tunnel reports established, but branch users cannot reach one remote subnet.", steps: ["Confirm the intended source and destination prefixes are included in the VPN policy.", "Check routing in both directions and any firewall rules after decapsulation.", "Test reachability by address and inspect security association counters."], check: "Does an established tunnel guarantee every application is reachable?", choices: ["Yes, it bypasses all routing and policy", "No, routes, selectors, and post-tunnel policy still matter", "Yes, VPNs replace DNS", "No, because tunnels cannot carry IP"], answer: 1, explanation: "Tunnel establishment does not guarantee the right prefixes are routed or permitted; the traffic selectors and post-decryption path also matter."}
  ),
  "wireless-security": lesson(
    ["Explain wireless authentication, encryption, and client isolation.", "Select safer WLAN practices for personal, enterprise, and guest networks."],
    ["Wireless frames travel through shared radio space, so authentication and encryption protect network access and data confidentiality. WPA2/WPA3 use stronger protection than obsolete WEP; use current supported modes and secure configuration.", "Personal mode uses a shared passphrase, which can be difficult to revoke for one user. Enterprise mode uses 802.1X and an authentication server for individual identities and policy.", "Guest networks should be segmented and restricted from internal services. Disable insecure convenience features where appropriate, maintain firmware, and validate both association policy and wired VLAN enforcement."],
    { caption: "WLAN security applies identity, encryption, and segmentation.", nodes: [{ title: "Client", subtitle: "Proves identity" }, { title: "WPA2/WPA3", subtitle: "Protects radio link" }, { title: "AP/controller", subtitle: "Applies WLAN policy" }, { title: "Guest VLAN/ACL", subtitle: "Limits reachable resources" }] },
    { title: "Isolate guest wireless users", scenario: "Visitors need internet access but must not reach internal servers.", steps: ["Create a guest WLAN with a suitable authentication policy.", "Map guest clients to a separate VLAN and apply restricted routing/firewall policy.", "Test internet access and confirm internal address ranges are unreachable."], check: "Which control most directly separates guest clients from internal networks?", choices: ["A unique SSID name only", "Guest VLAN plus restrictive Layer 3 policy", "Increasing the radio transmit power", "Changing DNS without filtering"], answer: 1, explanation: "An SSID name is not a security boundary by itself. VLAN segmentation and policy enforcement limit what guest clients can reach."}
  ),
  "automation": lesson(
    ["Explain how automation improves repeatability and reduces configuration drift.", "Identify safe stages for automating network changes."],
    ["Network automation uses scripts or platforms to collect state and apply repeatable configuration. It can reduce human repetition, but an incorrect template can scale a mistake across many devices.", "Reliable automation separates intended state from execution, uses version control, validates inputs, and reports outcomes. Idempotent operations converge devices toward a desired state without duplicating changes on every run.", "Start with read-only inventory or a small lab, add prechecks and rollback plans, then expand gradually. Human review remains valuable for high-impact changes and unusual exceptions."],
    { caption: "A controlled automation pipeline limits change risk.", nodes: [{ title: "Inventory", subtitle: "Select managed devices" }, { title: "Desired state", subtitle: "Versioned inputs" }, { title: "Precheck + apply", subtitle: "Validated execution" }, { title: "Verify", subtitle: "Compare resulting state" }] },
    { title: "Automate a safe baseline", scenario: "A team wants consistent NTP configuration across lab switches.", steps: ["Build an inventory limited to test devices and define the intended NTP state.", "Run a read-only check, then apply the change with review and logging.", "Verify synchronization on every target and handle exceptions explicitly."], check: "Why should a new automation be tested on a small scope first?", choices: ["To limit the impact of template or inventory errors", "Because automation cannot read device state", "To avoid keeping change records", "Because all devices must differ"], answer: 0, explanation: "A limited pilot exposes assumptions and errors before they affect a larger fleet; verification and rollback remain necessary."}
  ),
  "controllers": lesson(
    ["Compare centralized controller policy with per-device configuration.", "Distinguish control/management centralization from packet forwarding."],
    ["A controller provides a centralized point for policy, inventory, configuration, or analytics across network devices. It can improve consistency and visibility compared with managing every device manually.", "Software-defined networking separates policy intent and control functions from packet forwarding to varying degrees. The devices still forward packets, and controller connectivity or failure behavior must be understood.", "Controller APIs and templates depend on accurate inventory and compatible devices. Centralization can simplify operations but also creates a high-value management service that needs authentication, resilience, and change controls."],
    { caption: "Central policy coordinates distributed forwarding devices.", nodes: [{ title: "Operator", subtitle: "Defines intended policy" }, { title: "Controller", subtitle: "Coordinates configuration" }, { title: "Network devices", subtitle: "Apply local forwarding rules" }, { title: "Telemetry", subtitle: "State returns for visibility" }] },
    { title: "Roll out a controller policy", scenario: "A controller manages several access switches and a VLAN policy needs updating.", steps: ["Validate device inventory, target scope, and intended change in a lab.", "Stage or schedule the policy and inspect the planned device changes.", "Deploy to a pilot group, verify forwarding, then expand with monitoring."], check: "What continues forwarding packets in a controller-managed network?", choices: ["The network devices' forwarding plane", "The operator's browser only", "The DNS server", "An API response body"], answer: 0, explanation: "Controllers coordinate policy and management, while network devices continue to perform packet forwarding according to installed state."}
  ),
  "ai-ml": lesson(
    ["Describe how analytics can detect deviations in network telemetry.", "Recognize limitations, validation needs, and human oversight for AI/ML outputs."],
    ["Machine-learning systems can analyze telemetry such as flow rates, latency, errors, and client behavior to identify patterns that differ from a baseline. This can help prioritize investigation when data volumes exceed manual review.", "An anomaly is a signal for investigation, not proof of an attack or root cause. Changes in workload, seasonality, sensor gaps, and mislabeled data can create false positives or hide important events.", "Use explainable evidence, validate detections against packet/device facts, protect telemetry privacy, and maintain human approval for disruptive actions. Models complement rather than replace networking fundamentals and operational judgement."],
    { caption: "Analytics identifies a signal; an operator validates the cause.", nodes: [{ title: "Telemetry", subtitle: "Counters, flows, events" }, { title: "Baseline/model", subtitle: "Learn expected patterns" }, { title: "Anomaly alert", subtitle: "Candidate issue" }, { title: "Operator", subtitle: "Validate and respond" }] },
    { title: "Investigate an anomaly alert", scenario: "An analytics dashboard flags an unusual traffic spike on a branch uplink.", steps: ["Check the alert window, sensor coverage, and baseline context.", "Correlate with interface counters, flow records, and approved change events.", "Classify the cause before applying any traffic-control action."], check: "How should an anomaly alert be treated?", choices: ["As proof of compromise requiring immediate shutdown", "As a prompt to validate evidence and context", "As an authoritative routing update", "As a replacement for syslog"], answer: 1, explanation: "Analytics highlights unusual behavior but may produce false positives; corroborate it with device, traffic, and operational evidence."}
  ),
  "rest-apis": lesson(
    ["Explain REST resource access using common HTTP methods and status codes.", "Describe safe API authentication and request verification."],
    ["A REST-style API exposes resources through URLs and uses HTTP methods such as GET to retrieve, POST to create or trigger, PUT/PATCH to update, and DELETE to remove, depending on API design.", "Requests and responses carry status codes: 2xx generally indicates success, 4xx a client/request problem, and 5xx a server-side problem. An API may return structured JSON, but a successful HTTP status does not always mean an operation completed as intended.", "Use documented endpoints, least-privilege tokens, HTTPS, and careful handling of secrets. Validate response content and device state; avoid retrying non-idempotent operations blindly."],
    { caption: "An API request names a resource and receives a response.", nodes: [{ title: "Client", subtitle: "Authenticated request" }, { title: "HTTP method + URL", subtitle: "Action on resource" }, { title: "API service", subtitle: "Validate and execute" }, { title: "Status + data", subtitle: "Response to verify" }] },
    { title: "Read device status with an API", scenario: "An automation client needs interface operational status without changing configuration.", steps: ["Use a documented GET endpoint with a read-only credential over HTTPS.", "Check the HTTP status and parse the expected response fields.", "Compare the returned interface state with an independent device view."], check: "Which HTTP method is conventionally used to retrieve a resource?", choices: ["GET", "DELETE", "PATCH", "TRACE"], answer: 0, explanation: "GET conventionally retrieves a resource. Check the API documentation and verify the response data as well as its status."}
  ),
  "json": lesson(
    ["Read JSON objects, arrays, strings, numbers, booleans, and null values.", "Use JSON structure to interpret an API response accurately."],
    ["JSON represents structured data with objects enclosed in braces and key/value pairs, and arrays enclosed in brackets. Keys and string values use double quotes; commas separate elements.", "Values can be strings, numbers, true, false, null, objects, or arrays. A field's type matters: the string \"true\" is not the boolean true, and an absent field differs from a present null field.", "When consuming network data, validate expected fields and handle missing or malformed values. JSON syntax structures data but does not define what a field means; the API schema supplies that context."],
    { caption: "Nested JSON carries typed fields in a predictable structure.", nodes: [{ title: "Object", subtitle: "Named key/value fields" }, { title: "Array", subtitle: "Ordered collection" }, { title: "Typed values", subtitle: "String, number, bool, null" }, { title: "Consumer", subtitle: "Validate expected schema" }] },
    { title: "Interpret interface JSON", scenario: "A response contains {\"name\":\"Gi0/1\",\"up\":true,\"speed\":1000}.", steps: ["Identify the object and its three key/value pairs.", "Read the boolean status separately from the speed number.", "Check that required keys exist before using them in automation."], check: "What is the JSON type of the value true?", choices: ["String", "Boolean", "Number", "Array"], answer: 1, explanation: "The unquoted literal true is a JSON boolean. Quoted \"true\" would instead be a string."}
  ),
  "config-tools": lesson(
    ["Describe desired-state configuration management.", "Compare repeatable tool runs with manual one-off changes."],
    ["Configuration-management tools such as Ansible use inventories, variables, and tasks to apply repeatable changes. Infrastructure-as-code systems can also model resources and dependencies so changes are reviewed and tracked.", "A desired-state workflow compares current state with declared intent and applies necessary changes. Idempotence helps repeated runs converge without creating duplicate configuration, though not every operation is naturally idempotent.", "Protect secrets with an approved vault, review diffs, scope inventories carefully, and validate after application. Tool output alone is not enough: verify the live network state and preserve rollback options."],
    { caption: "Declared intent is applied, then compared with live state.", nodes: [{ title: "Inventory", subtitle: "Target devices and groups" }, { title: "Playbook/state", subtitle: "Reviewed intended change" }, { title: "Execution", subtitle: "Apply repeatably" }, { title: "Verification", subtitle: "Confirm actual result" }] },
    { title: "Use a playbook safely", scenario: "Ansible will configure an approved NTP server on a group of test routers.", steps: ["Limit inventory to the test group and keep credentials in an approved secret store.", "Review the playbook diff and run a check/dry-run mode where supported.", "Apply, inspect per-device results, and verify NTP synchronization."], check: "What is the main benefit of an idempotent configuration task?", choices: ["Repeated runs converge without duplicating the intended change", "It guarantees the network has no outages", "It hides all configuration diffs", "It removes the need for inventory"], answer: 0, explanation: "Idempotence makes repeated application safe with respect to the declared state, but it does not replace review, scoping, or verification."}
  ),
  "dna-center": lesson(
    ["Describe Cisco DNA Center's role in centralized campus management.", "Explain SD-Access fabric concepts at a high level."],
    ["Cisco DNA Center (now also branded Cisco Catalyst Center in current product naming) provides centralized campus provisioning, assurance, and policy workflows. It coordinates managed infrastructure but does not replace every device's forwarding role.", "SD-Access uses a fabric approach to separate endpoint identity and policy from the underlying physical topology. Fabric edge nodes connect endpoints, while control-plane and border functions support endpoint reachability and external connectivity.", "Successful deployment depends on supported hardware/software, underlay IP reachability, identity/policy design, and careful migration planning. Central automation should be staged and verified because a fabric-wide policy mistake can have broad impact."],
    { caption: "Campus fabric roles coordinate identity and forwarding.", nodes: [{ title: "Endpoint", subtitle: "Connects at fabric edge" }, { title: "Fabric edge", subtitle: "Access and policy enforcement" }, { title: "Control plane", subtitle: "Endpoint location information" }, { title: "Border", subtitle: "External network connectivity" }] },
    { title: "Plan a fabric onboarding", scenario: "A campus team wants a consistent policy for a new user group across managed access switches.", steps: ["Validate platform support, underlay reachability, and the target policy scope.", "Stage the identity-to-policy mapping and review affected sites/devices.", "Pilot with test endpoints and verify segmentation and required services."], check: "In a high-level SD-Access design, what is a primary fabric-edge role?", choices: ["Connect endpoints and apply access policy", "Resolve every public DNS query", "Replace all physical switch ports", "Provide NTP stratum zero"], answer: 0, explanation: "Fabric edge devices connect endpoints and enforce the intended access policy; other fabric roles provide control-plane and border functions."}
  )
};
