export type QuizQuestion = {
  prompt: string;
  choices: [string, string, string, string];
  answer: number;
  explanation: string;
};

export const quizBank: Record<string, QuizQuestion> = {
  "network-devices": {
    prompt: "Which device forwards traffic between different IP networks?",
    choices: ["Access point", "Router", "Layer 2 switch", "Repeater"],
    answer: 1,
    explanation: "A router makes Layer 3 forwarding decisions between IP networks.",
  },
  topologies: {
    prompt: "In a star topology, what is the usual impact if one workstation cable fails?",
    choices: ["The entire LAN stops", "Only that workstation loses its link", "The core router reboots", "All VLANs merge"],
    answer: 1,
    explanation: "Each endpoint has a separate link to the center, so a single edge-link failure is usually isolated.",
  },
  cabling: {
    prompt: "Which medium is generally the better choice for a long building-to-building uplink?",
    choices: ["Unshielded copper patch cable", "Fiber-optic cable", "Console cable", "Telephone cable"],
    answer: 1,
    explanation: "Fiber supports longer distances and is less susceptible to electromagnetic interference than copper Ethernet.",
  },
  "interface-errors": {
    prompt: "A switch interface's CRC error counter keeps increasing. What should you investigate first?",
    choices: ["DNS search suffix", "Physical cable or interface issue", "OSPF router ID", "NTP stratum"],
    answer: 1,
    explanation: "CRC errors commonly point to a Layer 1 problem such as damaged cabling, interference, or a faulty interface.",
  },
  "tcp-udp": {
    prompt: "Which transport protocol provides sequencing and retransmission for reliable delivery?",
    choices: ["UDP", "TCP", "ICMP", "ARP"],
    answer: 1,
    explanation: "TCP provides ordered, reliable byte-stream delivery using acknowledgments and retransmission.",
  },
  "ipv4-subnetting": {
    prompt: "How many traditionally usable host addresses are in an IPv4 /26 subnet?",
    choices: ["30", "62", "64", "126"],
    answer: 1,
    explanation: "A /26 leaves 6 host bits: 2^6 = 64 total addresses. Subtract network and broadcast for 62 usable hosts.",
  },
  "private-ipv4": {
    prompt: "Which address is part of the RFC 1918 private IPv4 space?",
    choices: ["172.20.4.9", "172.40.4.9", "192.0.2.5", "198.51.100.8"],
    answer: 0,
    explanation: "The private 172 range is 172.16.0.0 through 172.31.255.255.",
  },
  "ipv6-addressing": {
    prompt: "What is the prefix length of a typical IPv6 LAN subnet?",
    choices: ["/32", "/48", "/64", "/128"],
    answer: 2,
    explanation: "A /64 is the standard subnet size used for most IPv6 LANs.",
  },
  "client-ip-config": {
    prompt: "A host can reach local devices but not remote networks. Which setting is a key first check?",
    choices: ["Default gateway", "Screen resolution", "Host name capitalization", "Switch serial number"],
    answer: 0,
    explanation: "The default gateway is the next hop a host uses to reach destinations outside its local subnet.",
  },
  "wireless-basics": {
    prompt: "What is a likely effect of nearby access points using overlapping channels?",
    choices: ["Improved roaming by default", "More radio interference", "Automatic VLAN routing", "Longer IPv4 prefixes"],
    answer: 1,
    explanation: "Co-channel or adjacent-channel interference can reduce wireless throughput and reliability.",
  },
  virtualization: {
    prompt: "What commonly connects virtual machines to each other and to a host's network interface?",
    choices: ["Virtual switch", "DHCP scope", "DNS zone", "Serial console"],
    answer: 0,
    explanation: "A virtual switch forwards frames among virtual interfaces and can connect them to a physical uplink.",
  },
  "switching-concepts": {
    prompt: "What does a switch normally do with an unknown unicast frame?",
    choices: ["Drop it immediately", "Flood it out eligible ports in that VLAN", "Route it to every subnet", "Convert it to a broadcast IP packet"],
    answer: 1,
    explanation: "If the destination MAC is absent from its table, the switch floods the frame within that VLAN (except the incoming port).",
  },
  vlans: {
    prompt: "What is the primary purpose of creating VLANs on a switch?",
    choices: ["Separate Layer 2 broadcast domains", "Encrypt all traffic", "Replace IP routing", "Increase cable distance"],
    answer: 0,
    explanation: "Each VLAN is a separate Layer 2 broadcast domain; communication between VLANs requires Layer 3 routing.",
  },
  trunks: {
    prompt: "How does an IEEE 802.1Q trunk distinguish most VLAN traffic?",
    choices: ["It adds a VLAN tag to Ethernet frames", "It changes the source IP to a VLAN number", "It uses a unique physical cable per VLAN", "It encrypts each frame"],
    answer: 0,
    explanation: "802.1Q inserts VLAN identification information into trunk frames; native VLAN traffic is handled specially.",
  },
  "discovery-protocols": {
    prompt: "What information can a neighbor discovery protocol such as LLDP provide?",
    choices: ["Details about a directly connected device", "Public DNS responses", "End-to-end application encryption", "The full internet routing table"],
    answer: 0,
    explanation: "CDP and LLDP advertise local neighbor details such as device identity, port, and capabilities.",
  },
  etherchannel: {
    prompt: "What is the result of a correctly formed EtherChannel?",
    choices: ["Multiple links appear as one logical link", "Each link becomes a separate VLAN", "Spanning Tree is disabled everywhere", "The switch becomes a router"],
    answer: 0,
    explanation: "EtherChannel bundles member interfaces into a logical port-channel for redundancy and aggregate capacity.",
  },
  "spanning-tree": {
    prompt: "Why does Spanning Tree place a redundant Layer 2 path into a non-forwarding state?",
    choices: ["To prevent switching loops", "To speed up DNS", "To create a new IP subnet", "To encrypt BPDUs"],
    answer: 0,
    explanation: "Blocking a redundant path prevents Layer 2 loops while preserving a backup path for failures.",
  },
  "edge-protection": {
    prompt: "What should BPDU Guard do if a protected edge port receives a BPDU?",
    choices: ["Disable the port due to unexpected spanning-tree traffic", "Convert the port to a trunk", "Make the device the root bridge", "Enable DHCP snooping"],
    answer: 0,
    explanation: "BPDU Guard protects endpoint-facing ports by err-disabling them when a BPDU suggests a switch was connected.",
  },
  "wireless-architecture": {
    prompt: "In a centrally managed WLAN, what is a common role of the wireless LAN controller?",
    choices: ["Manage AP configuration and WLAN policy", "Replace every Ethernet switch", "Resolve all client DNS requests", "Assign public IP addresses to the internet"],
    answer: 0,
    explanation: "A controller can centrally manage access points, WLAN configuration, and client policy.",
  },
  "wireless-connections": {
    prompt: "A wireless client joins an SSID mapped to a VLAN. Where does its wired traffic enter the LAN?",
    choices: ["Through the access point's wired connection", "Through the DNS server's console port", "Directly through the ISP", "Through an NTP multicast group"],
    answer: 0,
    explanation: "The AP bridges or tunnels client traffic into the wired infrastructure according to the WLAN design.",
  },
  "wlan-security": {
    prompt: "Which choice gives a personal/small-office WLAN protected authentication and encryption?",
    choices: ["Open authentication with no encryption", "WPA2-Personal with a strong passphrase", "Hidden SSID only", "Changing the channel name"],
    answer: 1,
    explanation: "WPA2-Personal protects a WLAN with a pre-shared key; hiding the SSID is not a substitute for security.",
  },
  "routing-table": {
    prompt: "A routing table entry lists a next hop. What does that address identify?",
    choices: ["The next router toward the destination", "The final application server in every case", "The source MAC address", "The subnet broadcast address"],
    answer: 0,
    explanation: "The next hop is the neighboring Layer 3 device to which the router forwards the packet.",
  },
  "route-selection": {
    prompt: "A destination matches both a /16 and a /24 route. Which route wins the longest-prefix match?",
    choices: ["/16 route", "/24 route", "Whichever was entered first", "Both routes are always used equally"],
    answer: 1,
    explanation: "The /24 is more specific and therefore wins the longest-prefix match for an address within that prefix.",
  },
  "static-routes": {
    prompt: "What does an IPv4 default route match?",
    choices: ["Only the local subnet", "Destinations with no more-specific matching route", "Only multicast destinations", "Only directly connected networks"],
    answer: 1,
    explanation: "The 0.0.0.0/0 route is the least-specific route and acts as a fallback when no better match exists.",
  },
  ospf: {
    prompt: "What must OSPF routers on a shared link establish to exchange routing information?",
    choices: ["A neighbor relationship", "A DHCP lease", "A DNS zone transfer", "An EtherChannel"],
    answer: 0,
    explanation: "Routers form OSPF adjacencies with compatible neighbors before exchanging link-state information.",
  },
  "first-hop-redundancy": {
    prompt: "What address do hosts normally use with a first-hop redundancy protocol?",
    choices: ["A virtual default-gateway address", "The switch management MAC only", "The ISP's DNS address", "The OSPF process ID"],
    answer: 0,
    explanation: "Hosts use a virtual gateway shared by redundant routers so gateway service can survive a router failure.",
  },
  nat: {
    prompt: "What is a common use of NAT at an internet edge?",
    choices: ["Translate private source addresses to an outside address", "Encrypt a wireless SSID", "Elect a spanning-tree root", "Resolve domain names"],
    answer: 0,
    explanation: "NAT commonly translates internal private addresses to routable outside addresses for external connectivity.",
  },
  ntp: {
    prompt: "Why synchronize network-device clocks with NTP?",
    choices: ["Correlate event timestamps across systems", "Prevent all packet loss", "Assign VLAN IDs", "Negotiate EtherChannel"],
    answer: 0,
    explanation: "Consistent time makes logs, alerts, and event sequences easier to compare during operations and troubleshooting.",
  },
  "dhcp-dns": {
    prompt: "Which service translates a human-readable host name into an IP address?",
    choices: ["DNS", "DHCP", "NTP", "SNMP"],
    answer: 0,
    explanation: "DNS resolves names to records such as IP addresses; DHCP dynamically provides host configuration.",
  },
  monitoring: {
    prompt: "Which service is primarily used to transport device event messages to a log collector?",
    choices: ["Syslog", "ARP", "TFTP", "LACP"],
    answer: 0,
    explanation: "Syslog transports event messages; SNMP is commonly used for monitoring and management data.",
  },
  qos: {
    prompt: "Which traffic is most likely to benefit from low latency and jitter?",
    choices: ["Real-time voice", "A nightly bulk backup", "A static archive", "An unused VLAN"],
    answer: 0,
    explanation: "Real-time voice is delay-sensitive, so QoS can classify and prioritize it during congestion.",
  },
  ssh: {
    prompt: "Why is SSH preferred over Telnet for remote device administration?",
    choices: ["SSH encrypts the management session", "SSH disables routing", "Telnet uses a stronger cipher", "SSH requires no authentication"],
    answer: 0,
    explanation: "SSH encrypts credentials and session traffic; Telnet sends them in clear text.",
  },
  "file-transfer": {
    prompt: "What is a sensible use of a network file-transfer service for a router?",
    choices: ["Copy a configuration backup to a managed server", "Negotiate a wireless channel", "Elect an OSPF DR", "Resolve an IPv6 link-local address"],
    answer: 0,
    explanation: "File-transfer services can move backups, images, and other files between a network device and a server.",
  },
  threats: {
    prompt: "Which action directly reduces exposure of a device-management service?",
    choices: ["Restrict management access to trusted sources", "Advertise the service publicly", "Disable all logging", "Use the same password everywhere"],
    answer: 0,
    explanation: "Limiting management access to authorized networks reduces the attack surface.",
  },
  "security-programs": {
    prompt: "What does the principle of least privilege mean?",
    choices: ["Give each user only the access needed for their role", "Give every user administrator rights", "Never update device software", "Allow shared anonymous accounts"],
    answer: 0,
    explanation: "Least privilege limits access to what a user or system needs to perform its assigned duties.",
  },
  "device-access": {
    prompt: "Which practice best protects network-device administration?",
    choices: ["Use authenticated encrypted management and limit trusted sources", "Enable open Telnet from every network", "Share one public password", "Disable authentication"],
    answer: 0,
    explanation: "Secure management combines authentication, encryption, and restricted reachability.",
  },
  acls: {
    prompt: "How are entries in a typical ACL evaluated?",
    choices: ["In order, stopping at the first match", "From the bottom upward only", "Randomly", "Only after NAT is disabled"],
    answer: 0,
    explanation: "ACL entries are processed top-down and the first matching permit or deny action is applied.",
  },
  "layer2-security": {
    prompt: "What can switch port security limit on an access port?",
    choices: ["The number of learned source MAC addresses", "The IPv6 prefix length", "The DNS TTL", "The OSPF area count"],
    answer: 0,
    explanation: "Port security can restrict which and how many MAC addresses are allowed on a switch port.",
  },
  aaa: {
    prompt: "Which AAA function determines what commands an authenticated administrator may run?",
    choices: ["Authorization", "Authentication", "Accounting", "Addressing"],
    answer: 0,
    explanation: "Authentication verifies identity; authorization determines permitted actions; accounting records activity.",
  },
  vpn: {
    prompt: "What is the main purpose of a VPN tunnel across an untrusted network?",
    choices: ["Protect traffic between endpoints", "Replace every routing protocol", "Increase the number of VLAN tags", "Translate DNS names"],
    answer: 0,
    explanation: "A VPN protects traffic through a logically private tunnel across an untrusted network.",
  },
  "wireless-security": {
    prompt: "Why is an open WLAN less secure than a properly protected WLAN?",
    choices: ["It lacks strong client authentication and link protection", "It always has a smaller subnet", "It uses IPv6", "It cannot use access points"],
    answer: 0,
    explanation: "Open networks do not provide the same authentication and encryption protections as secured WLANs.",
  },
  automation: {
    prompt: "What is a key benefit of automating a repeated configuration task?",
    choices: ["Consistency across devices", "Guaranteed zero vulnerabilities", "Removal of all change review", "Automatic physical cabling"],
    answer: 0,
    explanation: "Repeatable automation reduces manual variation and can make intended configurations more consistent.",
  },
  controllers: {
    prompt: "What is a common benefit of a network controller?",
    choices: ["Centralized visibility or policy management", "Replacing all endpoint operating systems", "Providing copper power to every device", "Eliminating IP addressing"],
    answer: 0,
    explanation: "Controllers provide centralized management abstractions while devices still perform data-plane forwarding.",
  },
  "ai-ml": {
    prompt: "How might machine learning help network operations?",
    choices: ["Identify patterns or anomalies in telemetry", "Guarantee that every alert is correct", "Replace all access control", "Create physical links"],
    answer: 0,
    explanation: "Analytics can find patterns in telemetry, but results still need context and validation.",
  },
  "rest-apis": {
    prompt: "Which HTTP method is conventionally used to retrieve a resource?",
    choices: ["GET", "DELETE", "PATCH", "TRACE"],
    answer: 0,
    explanation: "GET requests retrieve a resource; APIs commonly use POST to create and PUT or PATCH to update.",
  },
  json: {
    prompt: "In JSON, which syntax represents a collection of key-value pairs?",
    choices: ["An object in curly braces", "An array in parentheses", "A comment after //", "An XML tag"],
    answer: 0,
    explanation: "JSON objects use braces and named keys with values; arrays use square brackets.",
  },
  "config-tools": {
    prompt: "What does a configuration-management playbook help achieve?",
    choices: ["Repeatable configuration across multiple devices", "Automatic replacement of switch hardware", "Wireless spectrum allocation", "Public IP address registration"],
    answer: 0,
    explanation: "A playbook describes repeatable operations that can apply a consistent desired configuration.",
  },
  "dna-center": {
    prompt: "What is a high-level purpose of Cisco DNA Center in an enterprise network?",
    choices: ["Centralized network management and assurance", "Replacing all Layer 2 switching", "Serving as a client web browser", "Acting only as a copper transceiver"],
    answer: 0,
    explanation: "Cisco DNA Center is a network-management platform for centralized workflows, visibility, and assurance.",
  },
};
